crossroads/api.goodcity

app/models/concerns/push_updates.rb
app/models/item.rb
spec/models/item_spec.rb

When reviewer started reviewing items of offer by accepting or rejecting it, then assign him as a reviewer for that item's offer.

Assign reviewer

---

app/controllers/api/v1/offers_controller.rb
app/controllers/api/v1/packages_controller.rb
app/models/offer.rb
app/serializers/api/v1/offer_serializer.rb
app/serializers/api/v1/package_serializer.rb
db/migrate/20150331053636_link_package_to_offer.rb
db/migrate/20150401030717_add_delivered_by_to_offer.rb
db/schema.rb

* Add delivered_by to offer so we know how the offer was actually delivered
* Add reference to offer on package, helps in ember since "items.[].packages.@each.state" is not supported
* Allow offers that are under review or reviewed state to also be marked received

Update models for scenarios of marking offers/items received

---

app/models/concerns/push_updates.rb
app/serializers/api/v1/user_serializer.rb
spec/models/concerns/push_updates_spec.rb
spec/serializers/api/v1/user_serializer_spec.rb

Hi @mcm-ham 
Can you please review this changes? 
Thanks.

GCW-362 in push-updates, send required details of sender and avoid associated details

---

app/controllers/api/v1/twilio_controller.rb
app/jobs/accepted_call_notification_job.rb
app/jobs/send_donor_calling_notification_job.rb
app/models/offer.rb
app/services/push_service.rb
config/routes.rb
lib/goodcity/redis.rb

This PR has changes for
- Send call notification to Donor's recent active offer's private thread subscriber else supervisors
- Send call accept notification to Donor's recent active offer's private thread subscriber else supervisors other than who have accepted call.
- handle failure with twilio if any invalid response and notify via airbreak and play try-again message to caller
- handle call complete callback and set assigned worker's state back to offline.
Thanks.

GCW 411 inbound calls active numbers routing to Offer's private thread subscribers

---

app/controllers/api/v1/deliveries_controller.rb
app/models/ability.rb
db/schema.rb
spec/controllers/api/v1/deliveries_controller_spec.rb
spec/models/abilities/delivery_abilities_spec.rb

The following CanCanCan definition for `Delivery` was too open. It allows any logged in user to perform these actions on *any* delivery object, not just their own.
can [:create, :show, :update, :destroy, :confirm_delivery], Delivery
This has been tightened to only allow Donors to perform actions on deliveries that belong to their own offers.
can [:create], Delivery
if reviewer || supervisor
can [:index, :show, :update, :destroy, :confirm_delivery], Delivery
else
can [:show, :update, :destroy, :confirm_delivery], Delivery, offer_id: user_offer_ids
end
Specs have been added to confirm the permissions are locked down.
The `DeliveriesController#delete_existing_delivery` method has also been tightened to check permissions before deleting existing deliveries. As a general rule, user param data …

Delivery abilities

---

app/models/offer.rb

Hi,
This PR has some changes in scope to show all the offers of donor in Admin app except "draft". Please review and advice.
Thanks

GCW-1224 Admin-app Donor tab doesn't show past offers

---

Capfile
config/deploy.rb
config/initializers/rollbar.rb
config/sidekiq.yml

- use sidekiq to send error reports rather than synchronous thread.
- Integrate with ActiveJob to ensure reports are sent from inside
- Ignore our authorization headers (token)
- Capistrano deploy tracking
https://github.com/rollbar/rollbar-gem/blob/master/README.md

Gcw 1885 improve rollbar configuration

---

app/controllers/api/v1/versions_controller.rb
app/models/version.rb

Hi Team,
This PR is for ticket: https://jira.crossroads.org.hk/browse/GCW-1892
One of the Benchmark from live console:
old  query benchmark=> 1344.3962312303483 ms
new query benchmark => 449.34001518413424 ms
Please review and let me know if any changes are required.
Thanks

Gcw 1892 fix versions query

---

Gemfile
Gemfile.lock
app/models/order.rb
app/serializers/api/v1/order_serializer.rb
db/migrate/20180620045905_add_submitted_by_id_to_orders.rb
db/migrate/20180620045951_add_submitted_at_to_orders.rb
db/schema.rb

Hi Team,
This PR adds functionality to add timestamp and user detail when GC Order is Submitted.
It also updates OrderSerializer to send the same details.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2005
Note: This PR also upgrade `sprockets` gem to `3.7.2`

GCW 2005 order submission details

---

app/serializers/api/v1/order_transport_serializer.rb

Hi Team,
This PR includes serializer changes for feature of transport_detail page pre-filled if it was already filled up user.
Transport detail stays the same even after refreshing the page.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2009

GCW-2009 serializer changes

---

app/models/organisations_user.rb
app/services/twilio_service.rb
config/locales/en.yml
config/locales/zh-tw.yml

Hi Team, 
This PR is to change sms text which is sent if any user is added to organisation from stock app. (i.e manage charity users feature).
https://jira.crossroads.org.hk/browse/GCW-2013
Previous text : Nokia from crossroads has added you to the GoodCity for Charities platform. Please download the app and log in using this mobile number.
New text : Nokia  has added you to the GoodCity for Charities platform. Please download the app and log in using this mobile number.
Thanks.

remove organisation name from charity sms

---

app/models/order.rb
app/models/user.rb
app/services/twilio_service.rb
config/locales/en.yml
config/locales/zh-tw.yml
spec/models/order_spec.rb
spec/services/twilio_service_spec.rb

Hi Team,
This PR adds feature of sending sms notification to Users with "order fulfilment" role whenever any new GoodCity order is submitted.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2046
Please review the PR and let me know if any changes are required.
Thanks

GCW-2033 new order sms notification for order fulfilment users

---

app/models/organisation.rb
spec/models/organisation_spec.rb

Hi Team,
This PR fixes issue: Organisation is not searchable when either name_en or name_zh_tw is nil.
https://jira.crossroads.org.hk/browse/GCW-2124
Please review.
Thanks.

fix for organisation search was not working when either name_en or name_zh_tw is empty

---

app/models/order.rb
spec/controllers/api/v1/orders_controller_spec.rb

Hi Team,
This PR is to make gc orders searchable while designating item from stock app.
https://jira.crossroads.org.hk/browse/GCW-2125
Please review and let me know in case of any changes.
Thanks.

Gcw 2125 make gc orders searchable on item designation

---

app/controllers/api/v1/orders_controller.rb
app/serializers/api/v1/order_serializer.rb
app/serializers/api/v1/order_shallow_serializer.rb
config/database.yml
spec/controllers/api/v1/orders_controller_spec.rb
spec/factories/orders_packages.rb

Add an option to fetch orders without any associations. This is used to generate the list of orders when designating an item (performance issues)

GCW-2155 filtered responses

---

app/controllers/api/v1/authentication_controller.rb
app/models/user.rb
spec/models/user_spec.rb

Hi Team,
This is PR is for login issue on browse. `Signup` action on controller used `creation_with_auth` which is expecting `app_name` because of which app was breaking. So, have added code for the same and also handled test cases accordingly.
Please review the PR.
Thanks.

Fixed: Browse login/Signup issue fixed by passing  app_name to creation_with_auth method.

---

app/controllers/api/v1/packages_controller.rb
app/models/package.rb
spec/controllers/api/v1/packages_controller_spec.rb

Matt noticed that we could search items on Stock which had not yet been received, or items which had no inventory numbers.
This PR is adding query options to filter those out in the search. (Will be added to the stock app soon)

ADD: Item search filters for state and inventory_number presence

---

app/models/order.rb

When deleting orders, we should:
* delete the related detail object
* delete any related goodcity_request records
* delete any related orders_packages
Can you see any problems with this approach?

When deleting some records, delete their related records.

---

app/models/order.rb
spec/controllers/api/v1/orders_controller_spec.rb

When searching for orders to which we can designate items, we **only** show the orders that matches any of the following rules : 
- The order is a **Draft StockIT** order 
This allows Recycling and LocalBoutique to appear in the results
- The order is in an **active state** (Submitted/Processing/Scheduled/Dispatching) **and** has a submitted_at timestamp
--> https://jira.crossroads.org.hk/browse/GCW-2198

Gcw 2198 order filtering for designation

---

config/schedule.rb
lib/tasks/subscription_sms_sent_reminder_at.rake

Hi Team,
This is PR for rake task to update `sms_reminder_sent_at ` to 24 hours from present time. I've also commented out cron job to run `SMS Reminder`. Once the rake is run on live, will uncomment the job.
Please review it and let me know if any change is required.

Rake task to update sms_reminder_sent_at time to 24 hours from present Time

---

app/services/subscriptions_reminder.rb

Hi Team,
This is PR for `sms_reminder_sent_at` update from `Time.now` to `Time.zone.now`.
Please review this PR and let me know if any change is required.

Subscription: sms_reminder_sent_at update changed from Time.now to Time.zone.now

---

app/models/holiday.rb
lib/classes/date_set.rb
spec/controllers/api/v1/holidays_controller_spec.rb

Quick notes: 
During debug I saw some of the tests are potentially faulty, so is the DateSet class. After fixing the bug it entered into a new part of the code and broke there (hence the addition of `.pluck(:holiday)`
I think a proper migration from `timestamp` to `date` is very much needed here
Some details on the issue ->
the `within_days` method searches for timestamps which are `> Time.now` , however holidays are stored with hour `00:00`.
Meaning that at `10am` is already out of that range

Fix bug where a holiday would show as available if it is today

---

app/jobs/socketio_send_job.rb
config/sidekiq.yml

This enables us to separate out jobs during stock take.

Put socketio push updates on to it's own queue.

---

.circleci/config.yml
app/controllers/api/v1/packages_controller.rb
app/models/concerns/package_filtering.rb
app/models/package.rb
db/migrate/20190129073952_add_indexes_to_package.rb
db/migrate/20190129081612_add_indexes_on_location.rb
db/migrate/20190131083340_add_indexes_to_packages_locations.rb
db/schema.rb
spec/controllers/api/v1/packages_controller_spec.rb
spec/models/concerns/package_filtering_spec.rb

Queries perform x1000 faster.
Notes:
- this speeds up free text search and the paginiation (COUNT) queries
- we've removed location free text search in order to ensure the query planner always chooses to use indexes
- switching rspec test suite to use `rake db:migrate` instead of `rake db:schema:load` - the migrations contain postgresql specific SQL that isn't captured inside schema.db

Added gin trigram indexes for free-text search. 

---

app/models/order.rb
spec/models/order_spec.rb

Hi Team,
This PR removes order sms notification for Order fulfilment users.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2368
Please review.

GCW 2368 remove sms notification for order fulfilment

---

app/models/location.rb
app/models/version.rb
db/migrate/20190201084112_add_indexes_to_versions.rb
db/schema.rb
spec/controllers/api/v1/versions_controller_spec.rb
spec/factories/versions.rb
spec/models/version_spec.rb
spec/serializers/api/v1/version_serializer_spec.rb

This is the next in a series of API speed improvements.
- JSONB columns (faster and natively indexed)
- Adjusted Location.recently_used method to use new partial index.
Please note, on a versions table with 1.2million rows, this migration can take upwards of 20 seconds.

Converted object and object_changes in versions table to JSONB column

---

app/models/subscription.rb
app/services/subscriptions_reminder.rb
config/schedule.rb
db/migrate/20190126035002_move_sms_reminder_at_to_user.rb
db/schema.rb
lib/tasks/subscription_sms_sent_reminder_at.rake
spec/factories/subscriptions.rb
spec/factories/users.rb
spec/services/subscriptions_reminder_spec.rb

Rewrote the code to conform to the following specifications:
Send 1 reminder if:
- recipient is donor AND
- messages have arrived since we last sent a reminder AND
- at least one message is still unread AND
- no other reminders have been sent to this user in the last 4 hours
Don't send a reminder if:
- no new message has been created since we last sent a reminder OR
- a new message has been created but it's less than 4 hours since the user last received a reminder OR
- the new message has been read already OR
- it was sent by the user
More generally
- Only ever alert for a message once
- If there is more than one new message, only send one SMS reminder.
- For users that have just signed up, don't message them for at least 4 hours

Gcw 2189 sms refactoring bug fixes

---

app/models/user.rb
app/services/channel.rb
spec/models/user_spec.rb
spec/services/channel_spec.rb

This improves separation of concerns as Channel names should live inside Channel and not in the User class.

Moved User#channels to Channels#user_channels

---

app/controllers/api/v1/authentication_controller.rb
app/models/ability.rb
app/models/concerns/message_subscription.rb
app/models/concerns/push_updates.rb
app/services/channel.rb
spec/controllers/api/v1/authentication_controller_spec.rb
spec/models/abilities/user_abilities_spec.rb
spec/models/concerns/message_subscription_spec.rb
spec/services/channel_spec.rb

Moves Browse channel logic fully into `app/services/channel.rb` and removes any responsibility from the `authentication_controller` to understand channel logic.
This also enables `register_device` to call the same channel logic and fixes a bug where empty channels were being fed to the Notification Service.
Also fixed case where a donor messages on an offer that has no reviewers. No reviewers were being alerted by now all reviewers will receive alerts.

Gcw 2335 notification fixes

---

app/controllers/api/v1/orders_controller.rb
app/controllers/api/v1/process_checklists_controller.rb
app/models/ability.rb
app/models/order.rb
app/models/orders_process_checklist.rb
app/models/process_checklist.rb
app/serializers/api/v1/order_process_checklist_serializer.rb
app/serializers/api/v1/order_serializer.rb
app/serializers/api/v1/process_checklist_serializer.rb
config/routes.rb
db/migrate/20190222023048_create_process_checklist.rb
db/schema.rb
spec/controllers/api/v1/orders_controller_spec.rb
spec/controllers/api/v1/process_checklists_controller_spec.rb
spec/factories/orders_process_checklists.rb
spec/factories/process_checklists.rb
spec/models/order_spec.rb
spec/models/process_checklist_spec.rb
spec/serializers/api/v1/order_serializer_spec.rb

There are 2 new tables:
* process_checklists  - This is just a lookup table on the different things to check which we'll configure via a settings page
* orders_process_checklists - This is a join table, if a record exist linking an order to a process_checklist row, that means it was checked. Unchecking something is simply a delete
Note: will probably modify this to forbid transition if the checklist isn't complete (need to check with Matt), there's already a `can_transition` method on the Order for that purpose.

Processing checklist

---

app/jobs/twilio_job.rb

Hi Team,
This PR will avoid sending SMS if the user does not have a mobile number. As we are now allowing user creation without mobile number from stock app. If we create any order on behalf of such user then it's not valid to try sending SMS to such user.
Please review.
Thanks.

send sms only if to mobile number is present

---

app/controllers/api/v1/packages_controller.rb
app/models/concerns/package_filtering.rb
spec/controllers/api/v1/packages_controller_spec.rb
spec/models/concerns/package_filtering_spec.rb

* Removed total_pages from search_stockit_it to improve performance (COUNTS are expensive).
Refactored PackageFiltering methods:
* to remove unneccessary SQL
* fixed a bug in state selections - modules do not like respond_to? methods.
* refactored specs

Improve performance of search_stockit_items method

---

app/models/user.rb
app/serializers/api/v1/user_serializer.rb
db/migrate/20190228150258_remove_permission_id_from_user.rb
db/schema.rb

Hi Team,
This PR removes a permission_id column from users and removes related code. We are no longer using permission_id at the user level as we have new role-permissions structure.
Please review.
Thanks.

Gcw 2431 remove permission id from users

---

lib/tasks/demo.rake
spec/controllers/api/v1/gogovan_orders_controller_spec.rb
spec/factories/items.rb
spec/factories/offers.rb

Updated demo factories to correctly form offers.
Offer traits are now cascading and build on each other.
Reviewed_by, closed_by etc are set at the right times.
This ensures `rake demo:load` creates full objects

Offer factory update

---

app/controllers/api/v1/offers_controller.rb
app/models/offer.rb
app/serializers/api/v1/delivery_serializer.rb
app/serializers/api/v1/offer_summary_serializer.rb
spec/serializers/api/v1/delivery_serializer_spec.rb

If an offer is in scheduled state, then include the delivery and schedule information in the summary serializer payload.

Added delivery/schedule payload for scheduled offers.

---

app/controllers/api/v1/order_transports_controller.rb
app/serializers/api/v1/order_transport_serializer.rb
db/migrate/20190311144106_remove_booking_type_id_from_order_transport.rb
db/schema.rb
spec/models/order_transport_spec.rb

Hi Team,
This PR removes booking_type_id from OrderTransport table as it is no longer required as we are saving booking_type against order now.
Please review.
Thanks.

Gcw 2362 remove booking type id from order transports

---

app/models/concerns/order_filtering.rb
app/models/order.rb
spec/controllers/api/v1/orders_controller_spec.rb

This PR adds sorting to orders search
The sorting **only** applies when searching for orders in active states.
This is will eventually be replaced by additional UI Filters to control sorting, but the staff here is finding it difficult to find urgent orders so we're adding that small workaround for now.

GCW-2511 sorted orders

---

app/models/mobile.rb
db/seeds.rb
spec/models/mobile_spec.rb

This PR adds 4,7,8 to the regex for mobile validations.

GCW-2517 add 4,7,8 in the regex for mobile

---

app/controllers/api/v1/appointment_slot_presets_controller.rb
app/controllers/api/v1/goodcity_requests_controller.rb
app/controllers/application_controller.rb
app/models/ability.rb
app/models/appointment_slot.rb
app/models/appointment_slot_preset.rb
app/models/concerns/push_updates_minimal.rb
app/models/goodcity_request.rb
app/models/order_transport.rb
app/models/package.rb
app/models/user.rb
app/services/channel.rb
app/services/push_service.rb
config/locales/en.yml
config/locales/zh-tw.yml
config/routes.rb
spec/controllers/api/v1/appointment_slot_presets_controller_spec.rb
spec/controllers/api/v1/authentication_controller_spec.rb
spec/controllers/api/v1/goodcity_requests_contoller_spec.rb
spec/factories/packages.rb
spec/models/appointment_slot_preset_spec.rb
spec/models/appointment_slot_spec.rb
spec/models/order_transport_spec.rb
spec/models/package_spec.rb
spec/services/channel_spec.rb
spec/services/push_service_spec.rb

This pull request adds live updates to : 
- appointment slots
- appointment slot presets
- packages 
Modifying the time of a preset will be rejected if that time is alredy used in a different preset
You'll notice I created a push class named `PushUpdatesMinimal` 
It's meant to be a much simpler version of the existing push updates, the idea is that it is a _configurable concern_ , instead of having one concern per model
Currently the only thing configurable is the channels we broadcast to.
Hopefully it'll grow to one day be robust enough to replace some of the current push update classes which are growing in complexity.
Notes:  
- The name of the class might change, I just needed to make the distinction with the current PushUpdate
- Any architectural suggestions are most welcome.
How to …

Live updates for Appointment slots and Packages

---

app/serializers/api/v1/package_serializer.rb

The name `package_images` was causing images not to be found on browse. Changing it for consistency

Rename of package_images to images

---

app/serializers/api/v1/package_serializer.rb

Since browse is now starting to use the standard package serializer, I'm adding some props that seem to be missing

Add allow_web_publish to package serializer

---

app/controllers/api/v1/orders_controller.rb
app/models/concerns/order_filtering.rb
app/models/order.rb
spec/controllers/api/v1/orders_controller_spec.rb

This is a cherry pick of the order sorting code.
It applies when we search for Active orders, showing the most urgent one first.
This is temporary and will eventually be replaced by a proper SQL fix

#April2019Release - Order Sorting

---

app/controllers/api/v1/gc_organisations_controller.rb
app/controllers/api/v1/users_controller.rb
app/serializers/api/v1/organisation_serializer.rb
spec/controllers/api/v1/gc_organisations_controller_spec.rb

As I was looking for performance issues with @steveyken  I found the following : 
- `OrganisationSerializer` included the `orders` association, which in turn created a **huge** payload
- The Stock app was fetching `organisations` one by one on the orders search page
- The Stock app was fetching `users` one by one on the orders search page
This PR applies the following fixes : 
- Remove the `orders` association from `OrganisationSerializer` , it's extremely heavy and is very unlikely to be needed
- Allow batch loading of `organisations` with `GET /organisations?ids[]=1&ids[]=2`
- Fix existing batch loading of `users`, there was a small String vs Integer type issue. Also the code was doing a `.split(,)` which is not necessary in the case of an array. So it handles both cases now

Batch loading of organisations and users

---

app/controllers/api/v1/offers_controller.rb
app/models/concerns/offer_search.rb
app/serializers/api/v1/offer_summary_serializer.rb
db/migrate/20190424063033_add_indexes_to_package_types.rb
db/migrate/20190424064348_add_body_index_on_messages.rb
db/migrate/20190424080441_add_notes_index_to_offers.rb

Changes:
- Switches from `postgres_ext_serializers` to `summary_serializer` (PES was struggling with the 4 levels of  joins in the search query.)
- Added GIN indexes to improve ILIKE query speed
- Use eager_loading to grab all associated data in one query (per association)

Improvements to speed up offer searches in admin app.

---

app/serializers/api/v1/order_serializer.rb
app/serializers/api/v1/order_shallow_serializer.rb

This PR removes the unread_messages_count attribute from order serialisers as its not required. 
Its calculated on the ember side.
Thanks

Remove unread messages count from serializers

---

app/controllers/api/v1/orders_controller.rb
spec/controllers/api/v1/orders_controller_spec.rb

Hi Team, this PR includes fixes for organisation missing on few orders.
The issue which was there was due to the reason of json params we were getting from the Ember side.
Whenever we update anything in the order from the logistics tab, the updateRecord method was called which caused the use of serializer method. In the params, organisation_id was sent null and due to that organisation was removed from the order, and similarly for stockit_organisation, it was updating the GC organisation id in the order.
In the params coming from client, we're sending `gc_organisation_id` which does not exist on orders table, so we need to manipulate the params so that we don't mess up the existing organisation_id present in the order.
I have modified the order_params just how the api likes it. This PR …

GCW-2576 organisation missing fix

---

app/controllers/api/v1/orders_controller.rb
spec/controllers/api/v1/orders_controller_spec.rb

This PR reverts organisation fix on api side, as it has broken order creation, will go ahead with the serializer fix on ember side.

Revert "GCW-2576 organisation missing fix"

---

app/services/subscriptions_reminder.rb
app/services/twilio_service.rb
lib/tasks/subscription_sms_sent_reminder_at.rake
spec/services/twilio_service_spec.rb

Hi Team,
I have removed extra slack message code added in subscription_reminders as I realized we already have code to manage that in twilio service.
I added id and name in slack message as it will help us in this case and can't see any drawback of adding it.
Please review.
Thanks.

Remove unwanted slack reminders

---

app/controllers/api/v1/users_controller.rb
app/models/ability.rb
app/models/order.rb
config/routes.rb
spec/controllers/api/v1/users_controller_spec.rb
spec/models/order_spec.rb

Hi Team,
This PR is for ticket GCW-2421- Adding total request counts. Since, we have common routes for fetching orders data in nested routes. Which will results in unnecessary request i.e orders_count, for data which is not required in other pages. So, I have added separate ajax request for orders_count on orders_summary page instead of adding it in users or orders payload.

GCW- 2421- Add total request count to order's contact summary

---

lib/tasks/fix_missing_organisations.rake

Earlier I was thinking of handling the scenario for users having multiple organisations as well, but looking at this data, i don't think we need that anymore.
```
Staging Data 
o = Order.where("organisation_id IS NULL and code ILIKE ?","GC-%").where.not(state: "draft").map(&:created_by).map(&:organisations).map(&:count)
=> [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] 
```
```
Prod Data => 
Order.where("organisation_id IS NULL and code ILIKE ?","GC-%").where.not(state: …
```

Add rake for fix missing organizations from orders

---

app/services/azure_notifications_service.rb

Hi Team,
This PR contains changes to make azure notifications compatible with fcm. Even if they have migrated to fcm tags are still gcm.
Consider doc: https://firebase.google.com/docs/cloud-messaging/send-message
Please review.
Thanks.

fix azure notifications with fcm

---

app/controllers/api/v1/packages_controller.rb
app/serializers/api/v1/donor_condition_serializer.rb

The API was sending different labels for donor_conditions in some cases, which caused inconsistencies with the browse app (As reported by Nokia). This PR normalizes the texts 
Couple of general rules to note about the code that was removed : 
```
"(CASE WHEN donor_conditions.id=1 THEN 'New'
WHEN donor_conditions.id=2 THEN 'Mixed'
WHEN donor_conditions.id=3 THEN 'Used'
WHEN donor_conditions.id=4 THEN 'Broken'
END)"
```
* We cannot hardcode IDs anywhere, since we can never guarantee that they match. e.g If the table was ever re-seeded or edited, we would likely have different IDs
* We want to avoid hardcoded strings in the code as they are hard to track and make it very hard to ensure consistency ('New', 'Mixed', etc)
Pretty basic stuff, but I thought I'd point it out anyways 😄

Remove hardcoded donor conditions

---

app/services/subscriptions_reminder.rb

This ensures the correct user and message state are related.

Alter SQL to filter offers in the join query

---

app/models/offer.rb
app/services/subscriptions_reminder.rb
spec/models/offer_spec.rb
spec/services/subscriptions_reminder_spec.rb

Start the SMS Reminder Sent At clock AFTER the initial system generated 'Thank you for your offer' message has gone out. We don't want to send user SMS about this message.

Don't send SMS reminders for initial 'thank you for your offer' message

---

app/models/concerns/package_filtering.rb

Hi Team,
This PR fixes issue of images not loading after first page on package search of browse.
Please review.
Thanks.

fix images are not loading after first page on browse item search

---

app/controllers/api/v1/offers_controller.rb
spec/controllers/api/v1/offers_controller_spec.rb

If a staff member sends `created_by_id` in the payload, it'll be applied to the created offer.

Staff can create offers with no donor

---

config/routes.rb

For old mobile apps. Tested it using postman hit the api endpoint for 
`localhost:4000/api/v1/browse/fetch_packages` and `localhost:4000/api/v1/packages`
Working fine for me.

redirect users to packages controller if they hit `browse/fetch_packages`

---

config/routes.rb

This PR contains a hot fix, where old mobile apps were giving an issue on LIVE. as they were pointing to `/browse/fetch_packages` which doesn't exist.
So this PR fixes that issue by redirecting the user to current endpoint i.e. `/packages`.
Thanks

#July Release#3 

---

app/models/concerns/offer_search.rb
spec/models/concerns/offer_search_spec.rb

Hi Team,
This PR is for removing search on active offers if no states selected in filters. If no states selected it should search on all offers. I have removed `where` clause for states in `offers_search` because there is already `states` filter in `offer_filters.rb` file (https://github.com/crossroads/api.goodcity/blob/master/app/models/concerns/offer_filtering.rb#L14).

Added all search on all states if no states selected 

---

app/models/ability.rb
db/permissions_roles.yml
lib/tasks/remove_can_manage_order_permission_from_charity_users.rake
lib/tasks/remove_permission_from_role.rake

This PR is a fix for the issue which was discussed in the call. (i.e Restrict user to view other user's order)
`rake 'goodcity:remove_permission_from_role[permission_name, role_name]'`
eg: 
`rake 'goodcity:remove_permission_from_role[can_manage_orders, Charity]'`

Restrict user to view other user's order

---

app/services/twilio_service.rb
spec/factories/users.rb
spec/services/twilio_service_spec.rb

Hi Team,
This PR will avoid calling Twilio job if user does not have a mobile number and will fix the issue of trying to send SMS on email id.
Please review.
Thanks.

send sms to only mobile numbers

---

app/controllers/api/v1/offers_controller.rb

This small tweak will improve the speed of the offers index controller and take the processing bottleneck out of postgres and put it in rails for now.

Use AMS direct and bypass postgres-ext for offers#index.

---

app/models/order.rb
spec/controllers/api/v1/orders_controller_spec.rb

HKD has requested the ability to search orders by beneficiary. This PR simply adds that.

GCW-2735 Search orders by beneficiary

---

app/controllers/api/v1/packages_controller.rb
app/models/ability.rb
app/models/package.rb
spec/models/abilities/package_abilities_spec.rb

It's very hard to describe all the things that were going wrong, but I'll try.
@steveyken could you fill in any important info worth knowing : )
We were seeing the following 2 main crashes
* The union was failing with `Cannot union relation with includes`
* Cancan abilities were conflicting with ext_serializers (duplicate and missing joins)
* Remove the `can_search_browse_packages` permission, it served no purpose to begin with --> that actually revealed some of the underlying issues
* Replace the union with a single query doing an `OR`
* Remove the ability for donors to index their packages -- > ideally we do want to keep that, but we couldn't really figure out how to fix the Cancan/serializers issue. Given that donors currently never index their packages it's safe to remove for the time …

Fix package 500 error

---

Gemfile.lock
app/models/concerns/message_subscription.rb
spec/models/concerns/message_subscription_spec.rb

Private messages a broadcasted to all supervisor all the time
- The first private message is broadcasted to all supervisors.
- All subsequent private messages are only broadcasted to supervisors that have posted something in the chat (either public or private)

Reduce number of supervisor subscriptions

---

app/models/concerns/message_subscription.rb
spec/models/concerns/message_subscription_spec.rb

Here's a fix for the message subscription rule.
The issue being:
- The tests were written with a `supervisor` user, therefore not necessarily a reviewer
- On private messages, we only subscribe everyone on the first message, but this would cause this line to trigger for all subsequent messages `user_ids += User.reviewers.pluck(:id) if [self.sender_id] == user_ids`  -- Something not caught when testing with a supervisor
- Although one line was using `reviewers`, the other was using `supervisors`, so I consolidated everything under `staff`
cc - @steveyken

Fix message subscription rules

---

app/models/concerns/message_subscription.rb
spec/models/concerns/message_subscription_spec.rb

Private notifications currently only go to supervisors, this extends them to Reviewers

Fix: reviewers also get private notifications

---

app/models/concerns/offer_search.rb
app/serializers/api/v1/offer_summary_serializer.rb
spec/models/concerns/offer_search_spec.rb
spec/serializers/api/v1/offer_summary_serializer_spec.rb

Hi Team,
This PR is for allowing search on company name for Offer search. Company name is also provided in `Offer Summary` serializer response. 

GCW- 2695- include company name &/or note in offer title and search

---

app/jobs/stockit_update_job.rb
spec/jobs/stockit_update_job_spec.rb

If a Stockit update sync results in a create (not an update), ensure GoodCity records the new stockit_id.

GoodCity correctly syncs when Stockit creates a new item

---

lib/tasks/cloudinary.rake

Our Cloudinary account was reaching full capacity (**97%**)
A lot of raw images matched the camera's native resolution (one of them was around 7000x4000)
This rake tasks takes the 500 largest images and downsizes them to FHD.
I ran this a few times:
`bundle exec rake cloudinary:optimize`
And voila ! Magic :
As of now we're at **40%** capacity, with still a thousand images to downsize. Looking good
Next step: Resizing the images before upload

Resize images on cloudinary

---

app/jobs/stockit_update_job.rb

Hi Team,
This PR fixes stockit_update_job and socket jobs going in loop.
Reason: 
update_attrubute fires callbacks and only skips validations unlinke  in rails 2.
https://maxivak.com/update_attribute-and-update_attributes-ruby-on-rails/
Please review.
Thanks.

GCW-2782 fix stockit_update_job and socket_io job going into loop

---

Gemfile.lock
app/models/inventory_number.rb
spec/models/inventory_number_spec.rb

This is the fix to ensure that inventory numbers reserved in the packages table are taken into account when choosing the next one.
There is one spec failure because the code is returning '000000' as the next number. If you create a package with inventory number '000000' then the spec passes. I think we should adjust the code to start counting from 1 rather than 0.
@patrixr  can I hand this to you?

Look in packages table for existing inventory numbers.

---

app/controllers/api/v1/packages_controller.rb

https://jira.crossroads.org.hk/browse/GCW-2808
BUG: On applying "No Image" Filter on Item search page, gives something went wrong. 
Items > Select State Filter > Apply "No Image" filter.
Please review the PR.

GCW-2808-On Item Search State Filter on applying Image "No Images" gives "Something went wrong"

---

app/controllers/api/v1/companies_controller.rb

BUG: Fixes company edit, earlier, update was not working if we do not put CRM id while editing the company.
Company edit, donor_details

Fix company edit and render error in case of failure

---

app/controllers/api/v1/deliveries_controller.rb
app/models/appointment_slot.rb
app/models/holiday.rb
app/models/schedule.rb
config/locales/en.yml
config/locales/zh-tw.yml
spec/controllers/api/v1/deliveries_controller_spec.rb

BUG: We suspect some timezone issue allows people to schedule deliveries on public holidays, this adds a backend check to ensure this never happens.
NOTE: I originally went with a model validation, but then realized the controller makes a ggv modification straight away, so I sneaked the verification in the controller to avoid that happening.
Donor app > Transport schedule

No schedule on public holidays

---

app/controllers/api/v1/inventory_numbers_controller.rb
spec/controllers/api/v1/inventory_numbers_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-2824
It fixes the rollbar issue: https://rollbar.com/crossroads_it/api.goodcity/items/395/
STEPS TO REPRODUCE BUG: 
- Receive item with an inventory number. 
- Click on the receive button. (try creating with inventory number which already exists so it will return 422 from API)
- Now try clicking on cancel button on-screen and nothing happens and it returns above rollbar issue. 
Cancel feature on a page -> Receive with inventory number on admin app.
Please review.
Thanks.

GCW-2824 fix inventory number remove end-point breaks sometimes

---

app/jobs/stockit_update_job.rb

https://jira.crossroads.org.hk/browse/GCW-2823
FIXES BUG: I am seeing this job in retry queue [Production]. It's trying to update item on stockit but it do not relates to any item on stockit also it do not have any inventory number. So ideally code should not try to perform sync operation.
https://crossroads-hk.slack.com/archives/GBJAFNVFB/p1569311435095900
Please review.
Thanks.

GCW-2823 fix StockitUpdateJob goes in retry loop

---

app/controllers/api/v1/packages_controller.rb
spec/controllers/api/v1/packages_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-2807
FEATURE: Added infinite-scroll on Items and Orders item search page.
This PR adds pagination to the search package endpoint.

GCW-2807-Add Infinite scroll on Items filters and search Item for Orders page.

---

lib/classes/package_category_importer.rb

https://jira.crossroads.org.hk/browse/GCW-2529
BUG: It fixes the issue of package_category_importer is not creating records in DB.
> PackageCategoriesPackageType.first_or_create(package_type_id:     package.id, package_category_id: package_category.id)
In this syntax, it checks table has a record or not. It does not consider our condition. Even if any single record exists in db then it will not create a new record.
> PackageCategoriesPackageType.where(package_type_id:  package.id, package_category_id: package_category.id).first_or_create
For this it checks for condition first and then if record with that condition do not exists in db then it creates new one.
https://github.com/crossroads/api.goodcity/pull/833
Please review.
Thanks.

fix package_category importer not creating any records in db

---

app/controllers/api/v1/package_types_controller.rb
app/models/package_type.rb
db/migrate/20190913102426_add_allow_stock_to_package_types.rb
db/schema.rb
lib/tasks/package_types.rake
spec/models/package_type_spec.rb

https://jira.crossroads.org.hk/browse/GCW-2781
FEATURE: Sync StockIt's `codes.status` field with a new field in GoodCity `package_types.allow_stock`
Also added rake task to update `package_types.allow_stock` with Stockit `codes.status`.
PackageType selection during in stock app will have types of `allow_stock` True.
https://bitbucket.org/crfdevs/stockit/pull-requests/56/gcw-2781-add-sync-status-column-to/diff

Gcw 2781 add and sync allow stock for package type

---

app/controllers/api/v1/lookups_controller.rb
app/models/computer.rb
app/models/computer_accessory.rb
app/models/concerns/subform_utilities.rb
app/models/country.rb
app/models/electrical.rb
app/models/lookup.rb
app/serializers/api/v1/lookup_serializer.rb
config/routes.rb
db/lookup.yml
db/migrate/20191030081621_create_lookups.rb
db/schema.rb
lib/tasks/create_lookups.rake
spec/controllers/api/v1/lookups_controller_spec.rb
spec/factories/lookups.rb
spec/models/lookup_spec.rb
spec/serializers/api/v1/lookup_serializer_spec.rb

Adds Lookups table for fixed attributes. eg, electrical frequency, electrical voltage, test_status etc.
LINKED TO PARENT BRANCH, 
i.e. `GCW-2812-support-additional-fields`

GCW-2812 add lookups for fixed values of some dropdowns

---

app/models/package_categories_package_type.rb

Touch on `package_categories_package_type` to clear the cache when the relationship to package_types changes

Cache clear: packages_categories

---

app/controllers/api/v1/orders_controller.rb
app/serializers/api/v1/order_serializer.rb

GCW-2779
- OrdersPackages were missing when doing `GET /orders/:id` because of weird Serializer logic. 
I added an explicit argument that defaults to false
- Including the orders_packages 'allowed actions'

Include orders_packages in orders#show

---

app/models/ability.rb
spec/controllers/api/v1/beneficiaries_controller_spec.rb

Live issue fix: Users need to be able to view beneficiaries created by the staff for their order

#Release - Nov19 : beneficiary ability fix

---

Gemfile
Gemfile.lock
lib/classes/package_detail_builder.rb

FEATURE: Subform fields
BUG: Comp test status sync was failing due to one minor miss. 
NOTE: For the lookup_ids that we have stored in our database, we have `comp_test_status` for computers and computer_acessories. So while building the parameters, code was just building it for electrical params. Due to that, the computer test status was not getting syced.
It is now fixed and now will work smoothly.

fix comp test status sync issue

---

app/jobs/twilio_job.rb
spec/jobs/twilio_job_spec.rb

Hi Team,
This PR fixes rollbar issue: https://rollbar.com/crossroads_it/api.goodcity/items/706/
As we have upgrade Twilio gem, the messages method does not work with the account and it has been moved to the client. 
Please refer doc: https://github.com/twilio/twilio-ruby
I have tested this fix from the console.
Please review.
Thanks.

fix twilio sms

---

app/models/computer.rb
app/models/concerns/subform_utilities.rb
app/models/package.rb
spec/models/package_spec.rb

https://jira.crossroads.org.hk/browse/GCW-2881
BUG: If there is any issue in the item form, or subform, it throws an error on API side which prevents it from creating bad data. But, however, item was getting created on stockit side as there was no check for this kind of behavior what so ever. After fixing the data and resubmitting, it used to throw remove node error which has been fixed in this PR https://github.com/crossroads/stock.goodcity/pull/556 .
Along with that, it also fixes some code, and make it better to understand now. 
Item Creation on stock app. Stockit Item sync.
https://github.com/crossroads/stock.goodcity/pull/556
https://bitbucket.org/crfdevs/stockit/pull-requests/69/remove-unwanted-validations/diff

GCW-2881 inventory number already exists fix

---

app/services/stockit/item_sync.rb

BUG: Specify bug 
If item is updated, (any attribute of item is updated). It sends a sync request, which sends detail_id of api to stockit and creates a bad entry. This PR fixes that.

remove unwanted params which are causing issue in sync

---

app/models/concerns/message_subscription.rb
spec/models/concerns/message_subscription_spec.rb

https://jira.crossroads.org.hk/browse/GCW-2902
BUG: For an offer that has been created by an admin (not a donor), when a reviewer subsequently reviews the item and closes the offer, notifications are sent to all supervisors because the system thinks nobody is listening.
The fix is to avoid sending notifications to all staff when there is no donor. This affects just the 'donor' channel and not the 'private' supervisors messaging channel.
Offers -> Messages

Don't send notifications to all admins if there is no real donor.

---

app/controllers/api/v1/gc_organisations_controller.rb
app/models/concerns/fuzzy_search.rb
app/models/organisation.rb
db/migrate/20191204035945_add_indexes_to_organisations.rb
db/schema.rb
lib/classes/packages_inventories_importer.rb
spec/factories/packages.rb
spec/models/concerns/operations/stock_operations_spec.rb
spec/models/organisation_spec.rb

This is a first version of a `FuzzySearch` module, which I've plugged in to the Organisations model
Notes:
It is far from perfect, but Nokia mentioned people were having many problems especially with searches like : `'The ABC Foundation'` which are stored in the database as `'ABC Foundation, The'`
Speed can become a potential issue when searching through many fields, luckily that's not the case for Organisations. If we ever want to use it with Orders, we'll definitely need to assess performance and make improvements.
Other:
- Added a couple of sanity checks to the packages_inventory_importer. The changes were tiny so I squeezed them into this PR

Fuzzy organisation search

---

app/models/concerns/offer_filtering.rb

BUG: Fixes SQL injection issue in `order(...)` method
According to https://rails-sqli.org/#order the Model.order method is vulnerable to SQL injection (edge case)
We sanitize the order parameter and add an extra case for the scheduled join table.

Fixed SQLI issue by sanitizing sort_column options.

---

app/models/concerns/operations/location_operations.rb
spec/controllers/api/v1/booking_types_controller_spec.rb
spec/models/concerns/operations/location_operations_spec.rb

I noticed the move operation was registering a 'gain' and 'loss' instead of the 'move' action.
As of now it has no impact because loss/gain aren't yet used
This PR simply replaces the action used to 'move'
Fixed a test that was failing randomly

Inventory move action fix

---

app/controllers/api/v1/orders_packages_controller.rb
app/models/orders_package.rb

https://jira.crossroads.org.hk/browse/GCW-2932
FEATURE: Speeds up the `orders_packages` endpoint by using eager_loading strategies.
At a rough estimate (on a dev machine), this halves the request time (445ms is down to 275ms) and the DB load drops from 100ms to 33ms.
Before this code, the Rails log would show lots of repetitive queries when serializing json for `/orders_packages?order_id=11` requests.
```
OrdersPackage Load
Package Load
Location Load
PackageType Load
Image Load
OrdersPackage Load
Package Load
Location Load
PackageType Load
Image Load
OrdersPackage Load
Package Load
Location Load
PackageType Load
Image Load
OrdersPackage Load
Package Load
Location Load
PackageType Load
Image Load
etc etc...
Completed 200 OK in 445ms (Views: 10.3ms | ActiveRecord: 99.0ms)
```
After using …

in Use eager_loading to avoid N+1 queries.

---

app/controllers/api/v1/orders_controller.rb
spec/controllers/api/v1/orders_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-2932
BUG: Provides the data to fix an incorrect count of 'Active' packages on the Order screen.
@abulsayyad123 this is just an API PR, you will need to use this count in a separate Ember PR (I've not written that). Also, note I've just implemented a count of the associated orders_packages, this includes all cancelled, designated and dispatched records. Is that the same as what is shown in the active tab?
Orders > 12345
Due to the infinite scroll feature, the count on the Active tab here is wrong.
The solution is to provide the total count in the JSON data 'meta' dict. For example:
PR #894  PR #895 
https://crossroads-hk.slack.com/archives/GBJAFNVFB/p1579250342013900

Added orders_packages_count to orders JSON payload

---

app/controllers/api/v1/users_controller.rb

BUG: If `params[:ids_param]` is called with a user id that doesn't exist in the DB then a 404 error is thrown. Better to just return the users that are available, if any, and let the client figure out what is missing.
NOTE: e.g. Stock app > Order listing (where a list of users is fetched) - a missing user was causing 50+ rollbar errors to be generated!

Don't return 404 if not all users can be found.

---

app/models/concerns/inventory_computer.rb
app/models/concerns/operations/designation_operations.rb
app/models/concerns/operations/order_fulfilment_operations.rb
app/models/concerns/orders_package_actions.rb
app/models/orders_package.rb
config/locales/en.yml
config/locales/zh-tw.yml
db/schema.rb
features/orders_packages_actions.feature
features/step_definitions/orders_packages_actions_steps.rb
lib/goodcity/errors.rb
spec/controllers/api/v1/booking_types_controller_spec.rb
spec/controllers/api/v1/orders_packages_controller_spec.rb
spec/controllers/api/v1/users_controller_spec.rb
spec/factories/locations.rb
spec/models/concerns/operations/designation_operations_spec.rb

* **before** `Operations.dispatch_full_qty(op)`
* **after**    `Operations.dispatch(op, from_location: opts[:location_id], quantity: opts[:quantity])`
An `orders_package` in a _designated_ state now has the following actions listed:
* undispatch _(only if partially dispatched)_
* cancel _(only if dispatch hasn't started)_
Meaning: If you partially dispatch an `orders_package`, you won't be able to cancel it unless you first undispatch whatever has been dispatched.
The `undispatch` action now undispatches the already dispatched quantity. As of now there is no such thing as a partial undispatch.
* Fixed issue where the "designated" quantity of a package didn't take into account the partially dispatched quantity
* Fixed tests that would randomly fail due to Factories using `rand()` , …

Partial dispatch

---

app/models/concerns/operations/order_fulfilment_operations.rb
app/models/concerns/operations/stock_operations.rb
app/models/item.rb
app/models/packages_inventory.rb
config/locales/en.yml
config/locales/zh-tw.yml
lib/goodcity/errors.rb
spec/models/concerns/operations/stock_operations_spec.rb
spec/models/package_spec.rb
spec/models/packages_inventory_spec.rb

This is the first part of [GCW-3025](https://jira.crossroads.org.hk/browse/GCW-3025)
**Note:** this PR adds internal features and tests but those are not used as of now
Those will be used via the admin app to record the initial quantity of a package
file : `models/concerns/operations/stock_operations.rb`
Usage:
```
Package::Operations.inventorize(package, location)
Package::Operations.uninventorize(package)
```
A package can only be uninventorized right after being inventorized. If it is modified in any way, the operation will be rejected
Added an `undo` method to the PackagesInventory method, allowing to revert an action by adding it's opposite action to the log
e.g
```
last_action = PackagesInventory.find_by(package_id: 1, action: 'inventory')
last_action.undo …
```

Inventorize operations

---

app/models/ability.rb
db/permissions_roles.yml
spec/models/abilities/orders_packages_abilities_spec.rb

BUG: Non-admin users are able to view all orders_packages. This PR resolves that by restricting it to just ones that belong to orders they created or submitted.
NOTE: This shouldn't be merged until Browse and Stock have been well-tested for 401/403 errors
https://jira.crossroads.org.hk/browse/GCW-2963
* Order -> List / Show
* Browse -> Create order, View dashboard, View order

Remove manage_orders_packages role and replace with finer grained security

---

app/models/concerns/operations/order_fulfilment_operations.rb
app/models/package.rb

https://jira.crossroads.org.hk/browse/GCW-2905
FEATURE: Now that we are moving towards a post-Stockit world, we need to handle cases where the code runs with Stockit turned off. In this case, when a new package is inventorized, we don't want to add it to Stockit and wait for a response.
Admin App:
* Receive package
* Create new item

Don't add inventory to stockit if it's disabled.

---

app/controllers/api/v1/cancellation_reasons_controller.rb
app/controllers/api/v1/orders_controller.rb
app/models/cancellation_reason.rb
app/models/order.rb
app/serializers/api/v1/order_serializer.rb
app/serializers/api/v1/order_shallow_serializer.rb
db/migrate/20191223131446_add_cancellation_reason_id_to_order.rb
db/migrate/20191223134926_add_visible_to_order_to_cancellation_reason.rb
db/order_cancellation_reasons.yml
db/schema.rb
lib/tasks/add_new_cancellation_reasons.rake
spec/controllers/api/v1/cancellation_reasons_controller_spec.rb
spec/factories/cancellation_reasons.rb
spec/models/cancellation_reason_spec.rb
spec/models/order_spec.rb

https://jira.crossroads.org.hk/browse/GCW-2931
FEATURE: 
1) Adding cancellation Reason for Orders on stock 
2) assigning default cancellation_reason of "Changed mind".  
3) removing cancellation reason on resubmitting the order.
Go to specific order. Click "Cancel order" popup appears with cancellation message and options.

GCW-2931-Request cancellation reason for orders

---

app/controllers/api/v1/packages_controller.rb
spec/controllers/api/v1/packages_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3035
Stock item search should only show items with inventory number but right now items without inventory numbers are visible in the stock app. It fixes same issue.
NOTE:  I have verified, We are not calling this endpoint from any other place so it's better to set it to true directly.
Thanks.

GCW-3035 only inventorise items should be visible on stock

---

app/controllers/api/v1/appointment_slots_controller.rb
app/models/appointment_slot.rb
app/models/goodcity_setting.rb
db/goodcity_settings.yml
spec/controllers/api/v1/appointment_slots_controller_spec.rb

Based on the setting `api.appointments.prevent_booking_until` , all appointment slots are marked as locked before that specific date.
This fix is made to solve the issue of blocking appointments during the Coronavirus phase

Coronavirus lock appointments

---

app/controllers/api/v1/appointment_slots_controller.rb
app/models/appointment_slot.rb
app/models/goodcity_setting.rb
db/goodcity_settings.yml
spec/controllers/api/v1/appointment_slots_controller_spec.rb

This is the release PR for the following changes:
Based on the setting api.appointments.prevent_booking_until , all appointment slots are marked as locked before that specific date.
This fix is made to solve the issue of blocking appointments during the Coronavirus phase

#Release: coronavirus lock appointments

---

Gemfile.lock
app/models/concerns/operations/order_fulfilment_operations.rb
app/models/order.rb
app/models/orders_package.rb
features/order_state_transitions.feature
features/step_definitions/order_state_transitions_steps.rb
features/support/env.rb
spec/models/concerns/operations/order_fulfilment_operations_spec.rb
spec/support/inventory_initializer.rb

This covers a few regressions Matt noticed
- Cancelling an order with dispatched orders_packages should not be possible
- Dispatching an orders_package of an `awaiting_dispatch` order should put the order in the `dispatching` state

Order state transition validations

---

app/serializers/api/v1/package_serializer.rb

https://jira.crossroads.org.hk/browse/GCW-2985
**Rollback** changes from PR https://github.com/crossroads/api.goodcity/pull/916
Instead of sending on-hand-quantity of packages, send available-quantity of packages to show packages on the browse app
(available-quantity = package-received-quantity - (desginated-quantity - partial-dispatched-quantity))
Used in Browse app https://github.com/crossroads/browse.goodcity/pull/513
NOTE: IF there is any conversation happened for current changes in any of the slack channel, …

GCW-2985 send available-quantity of packages to browse

---

app/serializers/api/v1/order_shallow_serializer.rb

https://jira.crossroads.org.hk/browse/GCW-3074
BUG: When we search for orders on the orders search page, order_shallow_serializer is called. In that serializer we are not sending the cancellation reason id. Due to which cancellation reason goes missing.
Adding this attribute in the order_shallow serializer fixes this issue.

GCW-3074 send cancellation id in response to fix it

---

db/migrate/20200226062814_add_extra_quantity_fields.rb

This is a cherry pick from ongoing work : https://github.com/crossroads/api.goodcity/pull/926/files
Matt wants to have those columns on the database (uninitialised) in order for him to start writing queries for his Qlik reports.
Until the other PR is merged, those will remain un-used

Add extra quantity fields as a separate migration

---

app/models/computer.rb
app/models/concerns/subform_utilities.rb
app/services/stockit/item_sync.rb
lib/goodcity/detail_factory.rb
lib/tasks/stockit_item_detail_import.rake
spec/lib/goodcity/detail_factory_spec.rb

This PR adds a rake task to manage previous data for packages. On stockit,
1. Fetch packages(items) from stockit
2. Check for details, if present, create a record for those details on GC
3. If not present, create a blank record on GC which will get synced to Stockit.
Package detail data.
Stockit PR link https://bitbucket.org/crfdevs/stockit/pull-requests/72

GCW-2890 rake for importing data for package detail from stockit

---

app/models/booking_type.rb
db/migrate/20200226111634_add_uniqueness_constraint_to_booking_types.rb
spec/controllers/api/v1/appointment_slots_controller_spec.rb
spec/controllers/api/v1/orders_controller_spec.rb
spec/controllers/api/v1/requested_packages_controller_spec.rb
spec/factories/booking_types.rb
spec/factories/orders.rb
spec/factories/process_checklists.rb
spec/models/booking_type_spec.rb
spec/models/order_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3051
- Added a unique index to the booking_types name_en column to prevent types with the same. name.
- Added uniq validation name_en and name_zh_tw column of booking type.
Please review.
Thanks.

GCW-3051 fix duplicate record creation for booking type

---

app/serializers/api/v1/offer_company_serializer.rb
spec/serializers/api/v1/offer_company_serializer_spec.rb

This PR is for sending `received_at` in `offer-company` serializer.
Issue: `offer-company` serializer was not sending `received_at` in response which resulted in UI bug.

added received_at in offer-company serializer

---

app/serializers/api/v1/offer_company_serializer.rb
spec/serializers/api/v1/offer_company_serializer_spec.rb

Hi Team,
This PR is for adding `received_at` on Offer-company serializer which resulted in UI bug on stock app.

FIX=> Added "received_at" on Offer-company serializer for UI bug on stock

---

app/controllers/api/v1/authentication_controller.rb
app/controllers/concerns/app_matcher.rb
app/serializers/api/v1/user_serializer.rb
spec/controllers/api/v1/authentication_controller_spec.rb
spec/serializers/api/v1/user_serializer_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3082
Removes the printers data from getting loaded in browse and donor app.
FEATURE: Specify feature name
BUG: Specify bug 
NOTE: Give a description of what this PR does. If it fixes any bug, specify cause of an issue and approach/solution added to fix that issue.
NOTE: IF there is any conversation happened for current changes in any of the slack channel, mention the slack message link.

GCW-3082 Printers data should not be loaded into donor app

---

app/controllers/api/v1/packages_controller.rb
app/models/concerns/operations/stock_operations.rb
app/models/packages_inventory.rb
app/models/storage_type.rb
config/locales/en.yml
config/locales/zh-tw.yml
db/migrate/20200312083123_add_max_unit_quantity_column_to_storage_type.rb
db/schema.rb
db/seeds.rb
db/storage_types.yml
spec/controllers/api/v1/packages_controller_spec.rb
spec/factories/packages.rb
spec/factories/storage_types.rb
spec/models/concerns/operations/stock_operations_spec.rb
spec/models/packages_inventory_spec.rb

Various fixes related to box/pallets and quantities:
Boxes and pallets should never have a quantity greater than `1`
This PR adds a `max_unit_quantity` column to the storage type in order to limit that number.
The `"gain"` action is forbidden on Boxes and Pallets
This raises a proper error when we try to add a negative amount of items to a box or pallet
Both @swatijadhav and I had basically implemented the same functionality. So there was a duplicate feature there. I consolidated both into a single method (her implementation, my function name)

Fixes: Box Pallet + Quantity

---

app/controllers/api/v1/packages_controller.rb
lib/goodcity/package_setup.rb
spec/controllers/api/v1/packages_controller_spec.rb

@abulsayyad123 Found an issue with the Split Quantity feature. 
I had removed a param from the controller, which was used by the split quantity.
The reason we didn't catch this issue was because the Splitter was unit tested, but not e2e tested. So I added that here

Fix package splitter controller params

---

lib/goodcity/package_setup.rb

As the data health fixes have been taking a while, this change will allow us to release quantities immediately.  And fix the bad data later on (probably once stockit is turned off)

Quantity setup: clamp negative values

---

app/models/concerns/inventory_computer.rb
app/models/concerns/secured.rb
app/models/package.rb

As titled, add a lock to avoid concurrent updates on the fields

Fix concurrent package quantity updates

---

app/controllers/api/v1/orders_controller.rb

https://jira.crossroads.org.hk/browse/GCW-3122
Fixes the bug when client summary tab is visited after the beneficiary is deleted for the order

GCW-3122 Deleting Beneficiary Gives Error

---

app/controllers/api/v1/packages_controller.rb

https://jira.crossroads.org.hk/browse/GCW-3145
`expiry_date` was passed through the stockit sync job, and was causing this rollbar error.

GCW-3145 removing filter for expiry_date

---

app/models/order.rb

This is a hot-fix for an issue where Stockit Shipments were not being updated because they were invalid. This happened because we added a constraint for `number_of_people_helped` to not be null, however this is not compatible with Stockit shipments and local orders.
Reverting change.

Fix case where Stockit will not send a value for number_of_people_helped

---

app/controllers/api/v1/orders_controller.rb
app/controllers/api/v1/orders_packages_controller.rb

When doing an order transition, e.g closing an order, we don't receive the updated `allowed_actions` of orders_packages. Which is expected by the UI.
This PR simply adds that in the response

GCW-3152 Return the orders_packages actions after a transition

---

app/models/printer.rb
db/migrate/20200522024354_add_printer_foreign_key_to_user.rb
db/schema.rb
spec/models/printer_spec.rb

Deleting a printer would previously leave users with an invalid printer_id.
This PR adds a foreign key constraint, and resets the user printers when the printer is deleted

Safe deletion of printers

---

app/models/inventory_number.rb
db/cancellation_reasons.yml
db/seeds.rb
spec/models/cancellation_reason_spec.rb
spec/models/inventory_number_spec.rb

https://jira.crossroads.org.hk/browse/GCW-2979
FEATURE: (by @bharat619)
Validate the inventory number is below a reasonable threshold. Avoid cases where people try to set '99999999999'
BUG: Fixed a bug whereby the wrong next inventory number was being issued
There were two defects causing the code to issue the wrong next available inventory number.
1. Using regex in Postgresql via ruby strings requires extra care due to string interpolation of ' and \
2. When writing multi-line SQL statements, it's best to use %{...} ruby syntax rather than opening " " so that everything is interpolated in a way that is compatible with PostgreSQL.
Stock: Add new item screen (getting repeated errors saying "Inventory Number is already taken")

Gcw 3093 Validate inventory numbers

---

Gemfile
Gemfile.lock
app/serializers/api/v1/item_serializer.rb
app/serializers/api/v1/package_serializer.rb
app/serializers/api/v1/stockit_item_serializer.rb
spec/controllers/api/v1/items_controller_spec.rb

We found a whole in postgres_ext_serializers which would ignore the type of a polymorphic relationship.
We've fixed it on our own fork here: https://github.com/crossroads/postgres_ext-serializers
This updates the Gemfile to point to the fixed version

FIX: postgres_serializer fix for polymorphism

---

app/controllers/api/v1/packages_controller.rb
app/models/package.rb
app/models/package_set.rb
lib/tasks/package_sets.rake
spec/models/package_set_spec.rb
spec/models/package_spec.rb

Issue: Admin creates packages for an item _before_ ever setting the `package_type` of that item. Therefore the api doesn't know how to initialize the set because it doesn't have a type.
This fixes that issue by initializing the set when the type is defined.

Fix package_set initialization

---

app/models/order.rb
spec/models/order_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3166
This PR restricts `draft` order in recently_used orders along with specs.

GCW-3166- restrict draft order in recent_orders

---

app/controllers/api/v1/api_controller.rb
app/models/packages_inventory.rb
config/locales/en.yml
config/locales/zh-tw.yml
spec/models/packages_inventory_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3183
`GAIN` actions were previously always forbidden on boxes due to their singleton state. However we should be allowed to restore the quantity of a box if it has been zero-ed by a `loss`.
If it has been zero-ed by a `dispatch`, we do not want to allow anyone to restore the quantity via a `GAIN`.
The overall rule is now the following:
User can modify the quantity of a box, within the [0-1] range _UNLESS_ the box has been dispatched

Allow gaining lost boxes, and prevent actions on dispatched boxes

---

app/controllers/api/v1/gc_organisations_controller.rb
app/models/ability.rb
app/models/organisation.rb
app/serializers/api/v1/organisation_serializer.rb
config/routes.rb
spec/controllers/api/v1/gc_organisations_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3182
- Added separate endpoint for fetching organisations orders with pagination
- Preload `orders` in `organisation` model for adding `ordersCount` field in `organisation` serializer.
- Added test cases for the same.
Please review this PR

GCW-3182-Issues with the Charity/Orders page

---

app/controllers/api/v1/gc_organisations_controller.rb
app/controllers/api/v1/packages_controller.rb
app/models/ability.rb
app/serializers/api/v1/stockit_item_serializer.rb
config/routes.rb
spec/controllers/api/v1/gc_organisations_controller_spec.rb

This PR 
- adds separate endpoint for fetching versions for Item.
- Remove version association in StockitItem Serializer.
- Renamed `organisation_orders` endpoint to `orders`

FIX=> Separate endpoint for fetching versions for Items.

---

app/models/ability.rb

https://jira.crossroads.org.hk/browse/GCW-3217
BUG: Order managers were getting a 403 error when writing notes on orders in the dispatching state.
Order -> Note

Allow order managers to edit in dispatching state.

---

app/models/ability.rb
spec/models/abilities/message_abilities_spec.rb

Hot fix
BUG: It wasn't possible to mark private messages as read after viewing them
Stock > Alerts > <choose private staff message>

Need to be able to mark_read on staff messages

---

app/models/user.rb
lib/classes/organisations_user_builder.rb
spec/controllers/api/v1/organisations_user_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3215
Fix the error when
- User already exists, create another charity user from stock app. The login of that particular user will result in an exception "User already exists"

GCW-3215 Add case insensitivity check while creating organisation users

---

app/models/concerns/stocktake_processor.rb
app/serializers/api/v1/stocktake_revision_serializer.rb
db/migrate/20200731075059_add_delta_to_stocktake_revision.rb
db/schema.rb
spec/models/concerns/stocktake_processor_spec.rb
spec/models/stocktake_revision_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3209
When a stocktake revision is processed, we save the difference under the `processed_delta` column. That is used to view the changes that occurred in the past

GCW-3209 Add processed_delta to stocktake_revisions

---

app/controllers/api/v1/messages_controller.rb
app/models/concerns/message_subscriptions.rb
app/models/message.rb
app/models/user.rb
spec/controllers/api/v1/messages_controller_spec.rb
spec/models/message_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3169
Update Message Default Scope, to allow users to access private messages who has message related permission (any one from ["can_manage_offer_messages", "can_manage_order_messages", "can_manage_package_messages"])

GCW-3169 Update Message Default Scope

---

config/locales/en.yml
config/locales/zh-tw.yml
lib/classes/organisations_user_builder.rb
spec/controllers/api/v1/organisations_user_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3246
On Charities, If an existing mobile number is entered on the Account Details page, an incorrect message appears: "Email has already been taken". This will handle the scenario.

GCW-3246 Wrong error message on creating user with new email and existing phone number

---

app/controllers/api/v1/stocktakes_controller.rb
spec/controllers/api/v1/stocktakes_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3209
`:comment` was missing from the controller's allowed params. Which would cause the comment not to be saved
Stocktake creation and listing

GCW-3209 FIX: Stocktake controller ignores comments

---

app/controllers/api/v1/packages_controller.rb
app/serializers/api/v1/package_set_serializer.rb

https://jira.crossroads.org.hk/browse/GCW-3249
In package serializer, when package-sets are passed in response, avoid passing packages again (to fix issue of sending non-published packages.)

GCW-3249 avoid sending set packages in package-serializer response

---

lib/goodcity/offer_utils.rb

https://jira.crossroads.org.hk/browse/GCW-3239
BUG: It was not possible to merge offers when the offer to be merged contained messages.
This broke when we introduced polymorphism to messages and forgot to update the `offer_id` to `messageable_id`
Admin app: Offer -> "Merge into"

Fix case where messages were not merged to new offer.

---

app/controllers/api/v1/orders_controller.rb
app/services/stockit/designation_sync.rb
lib/goodcity/import_designations.rb
lib/goodcity/scripts/import_designations.rb
spec/controllers/api/v1/orders_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3150
BUG: When Stockit sync'd Shipments over, GoodCity was treating them as LocalOrders. This stopped our Shipment specific UI from showing in GoodCity Stock app.
- Stockit sync.
- Existing data - I have corrected these entries in the GoodCity database.

Stop GoodCity from treating Stockit Shipments as LocalOrders.

---

app/jobs/print_label_job.rb

https://jira.crossroads.org.hk/browse/GCW-3276
BUG: The new printers_users table database changes were released but the code for printing to a printer was not updated to use the new model. To expediate the remediation, I have created a hotfix that will select the user's first printer in the printers_users table and print to that.
A subsequent fix should be deployed in the next release that chooses the printer based on the app being used.
Print label

A small bug fix to ensure printers continue to work with the new model.

---

app/services/sendgrid_service.rb

FEATURE: Prevents sending email in non production environments
Now that we have our own outbound email IP, we wish to maintain a good reputation. Sending email to potentially bad address
- Login via email on staging site
- Order emails on staging site

Don't send email in staging environment.

---

app/controllers/api/v1/offers_controller.rb
app/models/ability.rb
app/models/offer.rb
config/routes.rb
spec/models/offer_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3285
FEATURE: This PR adds feature to reopen closed/cancelled offers.

GCW-3285- Add a 'reopen' button to the offer details page

---

app/models/concerns/operations/stock_operations.rb
app/models/concerns/settings_validator.rb
db/package_types.yml
lib/goodcity/import_boxes.rb
spec/lib/goodcity/import_boxes_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3294
FEATURE: Provides an import script for migrating Stockit boxes and pallets. We will run this to import in-stock boxes/pallets just after the cutover, when these GoodCity features have been enabled.
Packages, Boxes, Pallets
- I haven't run the script yet. It needs testing.
- Need to write another similar script for importing pallets (there are some Stockit items on pallets)
- Need to write another script to put some boxes on pallets. This should be run once we have migrated all the boxes and pallets.

Migrate Stockit boxes and pallets to GoodCity

---

app/controllers/api/v1/api_controller.rb
app/controllers/api/v1/orders_controller.rb
app/controllers/api/v2/ability.rb
app/controllers/api/v2/api_controller.rb
app/models/beneficiary.rb
config/locales/en.yml
config/locales/zh-tw.yml
db/schema.rb
lib/goodcity/errors.rb
spec/controllers/api/v1/api_controller_spec.rb
spec/controllers/api/v1/appointment_slot_presets_controller_spec.rb
spec/controllers/api/v1/appointment_slots_controller_spec.rb
spec/controllers/api/v1/beneficiaries_controller_spec.rb
spec/controllers/api/v1/goodcity_settings_controller_spec.rb
spec/controllers/api/v1/package_sets_controller_spec.rb
spec/controllers/api/v1/process_checklists_controller_spec.rb
spec/controllers/api/v1/requested_packages_controller_spec.rb
spec/controllers/api/v2/ability_spec.rb
spec/controllers/api/v2/api_controller_spec.rb
spec/models/beneficiary_spec.rb

- orders.beneficiary_id nulled before beneficiary is deleted
- restored some commented tests
- api v2 role specification: empty role defaults to all role behaviour
- added a default error message for all foreign key related issue
- prevent frontend from setting `stockit_organisation_id` as it caused broken foreign keys

Fix: unlink beneficiary from order before deletion

---

app/models/package.rb
spec/controllers/api/v1/packages_controller_spec.rb

On designating a box or pallet to the order, a validation error pops up `Cannot change type of a box with items. Please remove the items and try again`
This will fix the scenario

Fix Validation Error on order designation

---

app/models/user.rb
spec/models/user_spec.rb

Users were forced to type the `+852` prefix when searching for mobile numbers

GCW-3285 Make mobile search on user tolerant

---

app/controllers/api/v1/users_controller.rb
app/models/user.rb
spec/controllers/api/v1/users_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3376
Fix the search of charity users - Instead of searching on the basis of role name, performs search on the approved or pending organisation status

GCW-3376 Fix User Charity Search

---

app/controllers/api/v1/organisations_users_controller.rb
app/controllers/api/v1/users_controller.rb
app/models/user.rb
config/routes.rb
spec/controllers/api/v1/organisations_user_controller_spec.rb
spec/controllers/api/v1/users_controller_spec.rb
spec/models/user_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3377
Removes the charity user role check on user search, and search user based on `organisations_users` status attribute

GCW-3377 Remove charity user check from user search

---

app/controllers/application_controller.rb

https://jira.crossroads.org.hk/browse/GCW-3382
This PR fixes the issue of `whodunnit` is setting null on update. `before_action :set_paper_trail_whodunnit` adds the `whodunnit` .

GCW-3382-whodunnit is setting null on update.

---

app/models/orders_package.rb
spec/models/orders_package_spec.rb

https://jira.crossroads.org.hk/browse/GCW-2626
Removes a line which set the orders_package quantity to 0

GCW-2626 Cancelling an orders_package doesn't zero the quantity

---

app/controllers/api/v1/organisations_controller.rb
app/serializers/api/v1/order_shallow_serializer.rb
spec/controllers/api/v1/orders_controller_spec.rb
spec/controllers/api/v1/organisations_controller_spec.rb
spec/serializers/api/v1/order_serializer_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3292
Fix the QA reported issues. Changes serialiser to send in `organisation_id` node instead of `gc_organisation_id` node

GCW-3372 Fix QA Issues

---

app/models/order.rb
config/locales/en.yml
config/locales/zh-tw.yml
db/schema.rb
spec/models/order_spec.rb

This was a frontend verification up until now. Which was bypassed when an order had more than 20 elements because pagination would not load all the records locally to find out whether all the orders_packages were actually in the right state

FIX: Prevent closing an order which has designated orders_packages

---

app/controllers/api/v1/package_types_controller.rb
spec/controllers/api/v1/package_types_controller_spec.rb
spec/factories/package_types.rb

Fixed GET package-types response.
Removed filter of `allow_stock` from the package-types response.
Slack Conversation: https://crossroads-hk.slack.com/archives/GBJAFNVFB/p1605076241204500

Fixed GET package-types response

---

app/controllers/api/v1/users_controller.rb
spec/controllers/api/v1/users_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3401
This PR catches error thrown while updating user and send it in response.

GCW-3401- Modifying a user's email to an email which is already in use should fail

---

features/step_definitions/orders_packages_actions_steps.rb
spec/models/package_spec.rb

This PR fixes staging failing cucumber spec because of current_user not available needed in `user-favorite` hook.

FIX => Failing Cucumber specs

---

app/serializers/api/v1/orders_package_serializer.rb
spec/serializers/api/v1/orders_package_serializer_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3403
This PR adds `updated_by` field in `orders_pacakge` serializer.

GCW-3403-Adding Missing actions on history tab

---

app/controllers/api/v1/packages_controller.rb
app/models/orders_package.rb
spec/controllers/api/v1/packages_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3403
This PR adds `version` in orders_package to generate versioning of designate action for Item history page.

GCW-3403 - Adding version in orders_package model for missing actions on history tab 

---

app/models/concerns/order_filtering.rb
spec/controllers/api/v1/orders_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3475
FEATURE: STOCK: user can filter orders of type "carry out" or "other"

GCW 3475 Adding carryouts and other to offer filter

---

app/controllers/api/v1/api_controller.rb
app/controllers/api/v1/requested_packages_controller.rb
app/controllers/api/v1/stocktakes_controller.rb
app/controllers/concerns/param_reader.rb
app/models/concerns/watcher.rb
app/models/stocktake.rb
app/models/stocktake_revision.rb
app/serializers/api/v1/stocktake_serializer.rb
db/migrate/20210112024003_add_counter_caches_to_stocktakes.rb
db/schema.rb
spec/controllers/api/v1/stocktakes_controller_spec.rb
spec/models/concerns/watcher_spec.rb
spec/models/stocktake_spec.rb
spec/serializers/api/v1/stocktake_serializer_spec.rb

Stocktakes now have the following counter caches : 
- `gains`
- `losses`
- `counts`
- `warnings`
Those were previously computed on the frontend from the list of stocktake revisions.
Which also means that we can now fetch the stocktakes _without_ their revisions, for faster load time on the main page. We're now doing that thanks to an `?include_revisions` query param.

GCW-3444 ADD: Stocktake counter caches

---

db/migrate/20210118111336_add_unique_constraints_to_order_on_transport.rb
db/schema.rb
spec/controllers/api/v1/appointment_slots_controller_spec.rb
spec/models/order_transport_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3476
This PR adds a `unique` constraint for `order_id` on the `orders_transport` table and added specs to test this feature.

GCW-3476-Some orders have more than one transport type

---

app/models/concerns/watcher.rb
app/models/stocktake.rb
spec/models/concerns/watcher_spec.rb
spec/models/stocktake_spec.rb

Stocktake revision population code now uses a single query, that allows:
- the removal of callback toggle on Watcher, that was causing the bug
- improved performance as it's all done in a single query now
Note: I would advise against using `thread_mattr_accessor` for the time being as it clearly hasn't been working as intented

GCW-3489: Remove watcher toggle

---

app/controllers/api/v1/ability.rb
spec/controllers/api/v1/order_transport_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3497
FEATURE: Error message shows '[object Object]' when attempting to edit Transport Type on closed order fix

GCW-3497- Add permissions to access order transport in closed and cancelled state

---

Gemfile.lock

The mimemagic gem was yanked. Updating to available version
Mac users will need to run `brew install shared-mime-info` before running `bundle install`

Fixed mimemagic debacle

---

app/serializers/api/v1/notification_serializer.rb
spec/serializers/api/v1/notification_serializer_spec.rb

GCW 3201 Adding shareable id to notification payload to add uid for the route of offer messages from notification in the browse app

GCW 3201 Adding shareable id to notification payload

---

app/models/offer.rb
spec/models/offer_spec.rb

Calling `send_message` on an Offer will not do anything if a donor is not present.

FIX: Offers.send_message without donor

---

app/models/user.rb
spec/models/user_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3576?focusedCommentId=46565&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-46565
Recycling otp_auth_key in signup endpoint if user is present.

GCW-3576- Add otp-auth-key recycling for signup pages

---

app/controllers/api/v1/messages_controller.rb
spec/controllers/api/v1/messages_controller_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3660
Fixed filtering of messages based on messageable-type and messageable-id.

GCW-3660 fixed filtering of messages

---

app/models/concerns/fuzzy_search.rb
spec/models/user_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3519
When Users are searched with last_name, show matched results at top of the list

GCW-3519 - Fix ordering issue when users are searched with last_name

---

app/models/concerns/stocktake_processor.rb
app/models/stocktake.rb
spec/models/concerns/stocktake_processor_spec.rb
spec/models/stocktake_spec.rb

:zap: 
- Disable auto-recount of counter caches during stocktake processing
- The counters will be re-counted only once at the end of the entire
process

Performance improvement: stocktake counters

---

app/controllers/api/v1/stocktake_revisions_controller.rb
app/controllers/api/v1/stocktakes_controller.rb
app/jobs/stocktake_job.rb
app/models/concerns/stocktake_processor.rb
app/models/stocktake.rb
app/models/stocktake_revision.rb
config/locales/en.yml
config/locales/zh-tw.yml
spec/controllers/api/v1/stocktake_revisions_controller_spec.rb
spec/controllers/api/v1/stocktakes_controller_spec.rb
spec/jobs/stocktake_job_spec.rb
spec/models/concerns/stocktake_processor_spec.rb
spec/models/stocktake_revision_spec.rb

- Stocktakes have 2 new states:
* `awaiting_process` -> This means they've been queued, used to avoid double-queuing
* `processing` -> This means Sidekiq is actively working on the stocktake
- Endpoint `/stocktakes/:id/commit` now returns immediatly, with the state updated to `awaiting_process`
- New files: `jobs/stocktake_job.rb`

Stocktakes: move processing to Sidekiq

---

app/controllers/api/v1/messages_controller.rb
spec/controllers/api/v1/messages_controller_spec.rb

On fetching messages, `messageable_type` should be present along with `messageable_id` values.

Fixed filtering of messages

---

app/controllers/api/v1/packages_controller.rb
app/models/packages_inventory.rb
spec/controllers/api/v1/packages_controller_spec.rb

Issue: 
The packages_controller endpoint was used for stockit sync, and was therefore overly permissive.
We found issues which allowed the admin app to set inventory numbers on records without a location_id. That in turn prevented the actual inventory step to take place (in packages_inventory).
This PR adds a workaround: we prevent setting the inventory_number without also providing a location.
Note: This is not a proper fix, a proper fix would require to rewrite these endpoints properly, and make inventory an actual action we take on a package.

FIX: packages controller enforces location_id when inventory_number is set

---

app/controllers/api/v1/stocktake_revisions_controller.rb
app/serializers/api/v1/stocktake_revision_serializer.rb
db/migrate/20210911024837_add_counted_by_ids_to_stocktake_revisions.rb
db/schema.rb
spec/controllers/api/v1/stocktake_revisions_controller_spec.rb
spec/models/stocktake_revision_spec.rb
spec/serializers/api/v1/stocktake_revision_serializer_spec.rb

Each revision of a stocktake now has a jsonb field called `counted_by_ids` which is an array of ids.
Whenever a user updates the quantity or the dirty flag, his/her id gets added to the list

ADD: counted_by_ids to stocktake_revisions

---

app/controllers/api/v1/messages_controller.rb
app/models/concerns/push_updates_for_message.rb
spec/controllers/api/v1/messages_controller_spec.rb
spec/controllers/api/v1/package_types_controller_spec.rb
spec/models/concerns/push_updates_for_message_spec.rb
spec/serializers/api/v1/notification_serializer_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3695
BUG: Fixed bug where state_value was being set to the wrong value
TLDR; When a message is created, the after_create hook fires which sends push_updates to subscribed users. To ensure the correct 'unread/read' state is sent, we adjust the virtual attribute 'state_value' for each user we send to. However, when this is all done, we were not resetting state_value back for the current_user and hence were likely to send the wrong value back to the user who created the message.
This PR fixes the problem but it does assume that the user identified by 'sender_id' (i.e. themself) is creating the message. It wouldn't work if an admin was allowed to create a message on behalf of another user. This currently isn't allowed and would be an unlikely use …

Fix bug with state_value for current_user

---

app/models/order.rb
spec/models/order_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3734
BUG: https://rollbar.com/crossroads_it/api.goodcity/items/4667/
NOTE: Order submission and confirmation emails would not be sent in cases where there was no DB translation for a particular package_type.
Order -> Email notifications

Fixed bug where order emails could not be sent due to undefined variable

---

app/controllers/api/v1/ability.rb
app/controllers/api/v1/offers_controller.rb
config/routes.rb
lib/goodcity/offer_utils.rb
spec/controllers/api/v1/offers_controller_spec.rb
spec/lib/goodcity/offer_utils_spec.rb

Adds the `/offer/:id/mergeable_offers` endpoint, to be used to fetch offers we are allowed to merge into

:sparkles: ADD: GET /offer/:id/mergeable_offers

---

lib/goodcity/user_utils.rb
spec/lib/goodcity/user_utils_spec.rb

https://jira.crossroads.org.hk/browse/GCW-3747
BUG: When some users were being merged, foreign key integrity would prevent the user from being deleted if they still had some 'soft deleted' messages in the messages table that referenced their sender_id.
Modified the user_utils class to ensure it can see soft deleted objects.
Audited other tables for the same bug. Added code for addresses and offers.
Merge users in Stock screen

Fixed merge user bug

---

Gemfile.lock

Issue https://github.com/crossroads/api.goodcity/issues/1322 [Hacktoberfest]
Update the `shoulda-matchers` version to the latest.
Verified above changes by running the entire specs locally.
cc @steveyken

Bump up shoulda-matchers version from 4.5.1 to 5.2.0

---

Gemfile.lock

Issue https://github.com/crossroads/api.goodcity/issues/1322 [Hacktoberfest]
Update the `timecop` version to the latest.
Verified above changes by running the entire specs locally.
cc @steveyken

Bump up timecop version from 0.9.4 to 0.9.5
