crossroads/api.goodcity

app/serializers/api/v1/crossroads_transport_serializer.rb, app/serializers/api/v1/offer_serializer.rb, db/crossroads_transports.yml, db/migrate/20150123125149_add_cost_to_crossroads_transports.rb, db/schema.rb, db/seeds.rb, doc/apipie_examples.json, spec/factories/crossroads_transports.rb, spec/factories/gogovan_transports.rb, spec/models/crossroads_transport_spec.rb
@steveyken Can you please review the changes? let me know if any changes needed.
Thanks.
=> Plan transport page

app/serializers/api/v1/crossroads_transport_serializer.rb, db/migrate/20150514091411_add_van_allowed_to_crossroads_transport.rb, db/schema.rb, spec/models/crossroads_transport_spec.rb
=> added column van_allowed to crossroads_transport

app/controllers/api/v1/deliveries_controller.rb, app/controllers/api/v1/gogovan_orders_controller.rb, app/models/gogovan_order.rb, app/models/gogovan_transport.rb, db/gogovan_transports.yml, doc/apipie_examples.json, lib/tasks/modify_ggv_transport_options.rake, spec/controllers/api/v1/deliveries_controller_spec.rb, spec/models/gogovan_transport_spec.rb
@mcm-ham @steveyken 
Please run following rake task, once it is deployed to live site:
Thanks.
=> GCW-334 Vehicle size can be chosen on GoGoVan booking form

app/controllers/api/v1/twilio_controller.rb, app/controllers/concerns/webhookable.rb, app/jobs/send_voicemail_job.rb, app/models/user.rb, app/models/version.rb, config/initializers/constants.rb, config/routes.rb, spec/jobs/send_voicemail_job_spec.rb, spec/models/user_spec.rb
References: 
Inbound Calls:
https://www.twilio.com/blog/2014/02/twilio-on-rails-integrating-twilio-with-your-rails-4-app.html :+1: 
https://www.twilio.com/docs/quickstart/ruby/client/incoming-calls
Twilio VM:
https://www.twilio.com/docs/quickstart/ruby/twiml/record-caller-leave-message
https://www.twilio.com/docs/api/twiml/record
=> Gcw 411 Inbound calls via Twilio

app/controllers/api/v1/twilio_inbound_controller.rb, app/services/twilio_inbound_call_manager.rb, spec/controllers/api/v1/twilio_inbound_controller_spec.rb, spec/services/twilio_inbound_call_manager_spec.rb
for review @swatijadhav 
I've tried to clean up the TCM class a bit. Have converted class methods to instance methods and also refactored ```from_admin?``` to be ```caller_is_admin?``` This should make things a bit easier to read.
=> Refactor Twilio Call Manager

app/controllers/api/v1/items_controller.rb, app/controllers/api/v1/offers_controller.rb, app/models/ability.rb, app/models/message.rb, app/services/azure_notifications_service.rb, config/routes.rb, doc/apipie_examples.json, spec/controllers/api/v1/items_controller_spec.rb, spec/controllers/api/v1/offers_controller_spec.rb, spec/models/abilities/item_abilities_spec.rb, spec/models/abilities/offer_abilities_spec.rb
https://jira.crossroads.org.hk/browse/GCW-531
=> Gcw 531 download message if missing from store on tapping-notification

app/controllers/api/v1/deliveries_controller.rb, app/models/ability.rb, app/models/delivery.rb, app/models/user.rb, app/models/version.rb
https://codeclimate.com/github/crossroads/api.goodcity/compare/refactoring#ratings
=> Refactoring

app/jobs/twilio_job.rb
handle Twilio::REST::RequestError in twilio send-pin job
=> GCW-994 handle error at twilio job

app/controllers/api/v1/braintree_controller.rb, app/serializers/api/v1/user_profile_serializer.rb, app/services/braintree_service.rb, db/migrate/20160607134338_add_is_success_to_braintree_transactions.rb, db/schema.rb
- fixed braintree transaction creation
- save success status of braintree transaction
- send failed braintree transaction status errors
=> GCW-923 fixed braintree transaction

app/controllers/api/v1/packages_controller.rb, app/serializers/api/v1/stockit_item_serializer.rb
@steveyken Can you please review these changes? Thanks
=> GCW-1111 search items and group with set together

app/models/location.rb
Hi,
This PR allows user to search location using concatenated building and area name.	
Thanks
=> GCW-1196 Search location using concatenated building and area

app/controllers/api/v1/stockit_designations_controller.rb, app/models/stockit_designation.rb
Hi Team,
This PR is for restring users from adding items to inactive orders.
Thanks.
=> GCW-1222-restrict-user-from-adding-items-to-inactive-orders

app/controllers/api/v1/packages_controller.rb, app/serializers/api/v1/donor_condition_serializer.rb
Hi,
This PR has changes in donorConditionSerializer for inline-editing stock item.
Thanks
=> GCW-1234 Changes for donor conditions

app/models/concerns/push_updates.rb, app/models/image.rb, app/models/package.rb, spec/controllers/api/v1/items_controller_spec.rb, spec/models/package_spec.rb
Hi,
This PR has some changes for live image updates on browse app.
Take a look and let me know if any further changes are required.
Thanks.
=> Live updates for images on Browse

app/controllers/api/v1/orders_controller.rb, app/models/ability.rb, config/routes.rb
This PR has some changes to confirm order for browse app.
=> Browse App:Confirm order changes

lib/goodcity/health_checks.rb, lib/goodcity/health_checks/base.rb, lib/goodcity/health_checks/dispatched_packages_order_id_check.rb, lib/goodcity/health_checks/location_stockit_id_nil_check.rb, lib/goodcity/health_checks/order_stockit_id_nil_check.rb, lib/goodcity/health_checks/orders_packages_order_id_check.rb, lib/goodcity/health_checks/package_stockit_id_nil_check.rb, lib/goodcity/health_checks/package_type_stockit_id_nil_check.rb, lib/goodcity/health_checks/received_packages_location_id_check.rb, lib/tasks/health_checks.rake, spec/lib/goodcity/health_checks/base_spec.rb, spec/lib/goodcity/health_checks/dispatched_packages_order_id_check_spec.rb, spec/lib/goodcity/health_checks/location_stockit_id_nil_check_spec.rb, spec/lib/goodcity/health_checks/order_stockit_id_nil_check_spec.rb, spec/lib/goodcity/health_checks/orders_packages_order_id_nil_check_spec.rb, spec/lib/goodcity/health_checks/package_stockit_id_nil_check_spec.rb, spec/lib/goodcity/health_checks/package_type_stockit_id_nil_check_spec.rb, spec/lib/goodcity/health_checks/received_packages_location_id_check_spec.rb, spec/lib/goodcity/health_checks_spec.rb
Use `rake health_checks`
Need more checks to be written now
=> Health check code.

lib/tasks/packages_add_received_quantity_data.rake
I've experiemented with using direct SQL updates for fixing quantity as this speeds things up. It makes a few assumptions in order to do so:
Assumes that:
* a Stockit update does not need to be sent
* a SocketIO notification won't be sent (admin users will need to F5 refresh and reload their mobile apps
* No other active record life cycle events need to be triggered
* When quantity is set to 0 for sent packages, Stockit does not need to be updated.
Can you review and confirm if the above assumptions are correct?
=> Using SQL to speed up the rake task.

app/controllers/api/v1/countries_controller.rb, app/controllers/api/v1/offers_controller.rb, app/jobs/poll_gogovan_order_status_job.rb, app/models/gogovan_order.rb, app/models/package.rb, app/services/braintree_service.rb, lib/tasks/update_timeslot.rake
https://github.com/bbatsov/ruby-style-guide#indent-conditional-assignment
=> Fix code climate issues

app/controllers/api/v1/packages_controller.rb, config/locales/en.yml, config/locales/zh-tw.yml
Reverts crossroads/api.goodcity#341
=> Revert "Gcw 1566 restrict negative values for quantity"

app/controllers/api/v1/packages_controller.rb, app/models/orders_package.rb, spec/controllers/api/v1/packages_controller_spec.rb
Reverts crossroads/api.goodcity#340
=> Revert "Gcw 1655 commit package chnages only if orders package is valid on designation"

app/controllers/api/v1/orders_controller.rb, app/serializers/api/v1/order_serializer.rb
In this PR order serializer will send organisation_id with order
=> add organisation in order serializer

app/models/package_type.rb, lib/tasks/stockit_codes.rake
Hi Team,
This PR is to create new package_type  record on api with all details when new code is created from stockit.
https://jira.crossroads.org.hk/browse/GCW-1728
Thanks.
=> GCW-1728 assign values for code created from stockit

app/models/package_type.rb, lib/tasks/stockit_codes.rake
Hi Team, 
This PR contains cherry-picked commits for fixing code sync issue from stockit for live deployment.
Commits are cherry-picked from PR : https://github.com/crossroads/api.goodcity/pull/365
https://jira.crossroads.org.hk/browse/GCW-1728
Thanks
=> #OctoberRelease1 - Fix new code creation sync issue

app/models/package.rb, spec/controllers/api/v1/packages_controller_spec.rb
Hi Team,
This PR is for ticket : https://jira.crossroads.org.hk/browse/GCW-1734
Thanks.
=> Gcw 1734 fix orders packages issue

app/controllers/api/v1/package_types_controller.rb
Hi Team,
This PR is for permitting params from stockit on code creation.
Thanks
=> show code in select list when created from stockit

app/controllers/api/v1/packages_controller.rb, spec/controllers/api/v1/packages_controller_spec.rb
Hi Team,
This PR is for ticket: https://jira.crossroads.org.hk/browse/GCW-1735
Thanks.
=> assign valid location_id on package instead of location's stockit_id

app/models/package.rb, spec/controllers/api/v1/packages_controller_spec.rb
Hi Team,
This PR is to fix issues mentioned on ticket : https://jira.crossroads.org.hk/browse/GCW-1741
Thanks
=> Gcw 1741 fix designation issues

app/controllers/api/v1/twilio_inbound_controller.rb
Hi Team,
This PR contains changes for ticket: https://jira.crossroads.org.hk/browse/GCW-1769
Thanks
=> GCW-1769 workaround for airbraik notify and use rollbar's error method

app/controllers/api/v1/organisations_users_controller.rb, lib/tasks/organisation_types.rake
Hi Team,
This PR contains minor syntax change.
Thanks.
=> syntax change

Gemfile, Gemfile.lock
Hi Team,
This PR fixes security vulnerability regarding sinatra and rack-protection gem.
Thanks.
=> Fix security vulnerability.

Gemfile, Gemfile.lock
Hi Team,
This PR fixes rails-html-sanitizer vulnerability.
https://jira.crossroads.org.hk/browse/GCW-1853
Thanks.
=> Fix vulnerability issue

app/models/user.rb
Reverts crossroads/api.goodcity#411
=> Revert "GCW-1861 fix issue: remove all roles for user should work"

lib/tasks/add_stockit_user.rake
Hi Team,
This PR is for ticket:  https://jira.crossroads.org.hk/browse/GCW-1866
Thanks.
=> GCW-1866 assign role to stockit user

spec/serializers/api/v1/packages_location_serializer_spec.rb
Hi Team,
This PR contains changes to improve packages_location serializer test coverage. Please review and let me know if any changes are required.
Thanks.
=> packages_location serializer specs

spec/serializers/api/v1/stockit_local_order_serializer_spec.rb
Hi Team,
This PR contains changes to improve stockit_local_order serializer test coverage. Please review and let me know if any changes are required.
Thanks
=> added stockit_local_order serializer specs to improve coverage

Gemfile, Gemfile.lock
Hi Team,
I have upgraded ffaker gem in this PR. Please review and let me know if any changes are required.
Thanks.
=> upgraded ffaker gem

spec/controllers/api/v1/addresses_controller_spec.rb, spec/controllers/api/v1/inventory_numbers_controller_spec.rb, spec/factories/inventory_number.rb, spec/factories/roles.rb, spec/factories/users.rb
Hi Team,
This PR contains changes to improve inventory_number controller test coverage. Please review and let me know if any changes are required.
Thanks.
=> added inventory_number controller specs to improve coverage

spec/serializers/api/v1/order_serializer_spec.rb
Hi Team,
This PR contains changes to improve order_serializer test coverage. Please review and let me know if any changes are required.
Thanks
=> added order serializer specs

app/controllers/api/v1/orders_controller.rb, app/models/order.rb, spec/controllers/api/v1/orders_controller_spec.rb
Hi Team,
This PR contains changes for ticket: https://jira.crossroads.org.hk/browse/GCW-1886
Thanks
=> Gcw 1886 fix orders controller data load issue

app/models/item.rb, app/models/orders_package.rb, app/models/package.rb, app/models/version.rb, app/services/stockit/item_sync.rb, spec/models/package_spec.rb
Hi,
This is PR for code climate issues.
Thanks
=> Code climate refactor

app/controllers/api/v1/packages_controller.rb
Hi Team,
This PR contains fix for Stock App: Show quantity items feature not working for items created from GC side
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-1887
=> GCW-1887 showQuantityItems fix for stock app

spec/controllers/api/v1/versions_controller_spec.rb, spec/factories/roles.rb, spec/factories/users.rb
Hi Team,
This PR contains specs for versions_controller to cover scenarios.
Please review and let me know if any changes are required.
Thanks
=> added specs for versions_controller

app/controllers/api/v1/packages_controller.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/factories/packages.rb
Hi,
This is PR for jira ticket 1880 - https://jira.crossroads.org.hk/browse/GCW-1880.
Please review it.
Thanks
=> Update quantity issue solved with test case

spec/controllers/api/v1/countries_controller_spec.rb, spec/factories/countries.rb
Hi,
This is PR for Countries controller Specs.
=> Specs for countries

spec/controllers/api/v1/cancellation_reasons_controller_spec.rb
Hi Team,
This PR contains specs to improve  test coverage of cancellation_reasons controller. Please review and let me know if any changes are required.
Thanks.
=> added cancellation_reasons controller specs

spec/controllers/api/v1/rejection_reasons_controller_specs.rb
Hi Team,
This PR contains specs to improve rejection_reason controller test coverage. Please review and let me know if any changes required.
Thanks.
=> rejection reason controller specs

app/controllers/api/v1/orders_controller.rb, app/models/ability.rb, app/models/concerns/push_updates.rb, app/models/order.rb, app/serializers/api/v1/order_serializer.rb, app/services/channel.rb, config/routes.rb, db/migrate/20180528084205_add_processed_at_to_orders.rb, db/migrate/20180529014537_add_process_completed_by_id_to_orders.rb, db/migrate/20180529014554_add_process_completed_at_to_orders.rb, db/migrate/20180529015651_add_cancelled_at_to_orders.rb, db/migrate/20180529015715_add_cancelled_by_id_to_orders.rb, db/migrate/20180529040914_add_closed_at_to_orders.rb, db/migrate/20180529040927_add_closed_by_id_to_orders.rb, db/schema.rb
Hi Team,
This PR adds state workflow for Order processing.
Jira Ticket:- https://jira.crossroads.org.hk/browse/GCW-1910
=> GCW-1910 stock order workflow

app/controllers/api/v1/orders_controller.rb, app/models/ability.rb, app/models/order.rb, app/serializers/api/v1/order_serializer.rb, config/routes.rb, db/migrate/20180604024724_add_dispatch_started_at_to_orders.rb, db/migrate/20180604025006_add_dispatch_started_by_to_orders.rb, db/schema.rb
Hi Team,
This PR includes feature to recover from Order terminal state for GCW:-1910.
Please review it and let me know if any changes are needed.
Thanks
=> GCW-1910 recovery from Order terminal state

app/controllers/api/v1/order_transports_controller.rb, app/models/ability.rb
Hi Team,
This PR adds functionality of editing order and transport detail for draft orders.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-1941
=> GCW:1941 Draft Order edit

app/controllers/api/v1/orders_controller.rb, app/models/ability.rb, app/models/order.rb
Hi Team,
This PR adds functionality to delete draft Order.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-1942
=> GCW:1942 Order cancellation

app/models/order.rb, app/models/user.rb, app/services/channel.rb, config/locales/en.yml, config/locales/zh-tw.yml
Hi Team, 
This PR is to notify order fulfilment user about new order submission from goodcity.
https://jira.crossroads.org.hk/browse/GCW-1909
Thanks
=> notify order fulfilment user about new order submission from browse app

app/models/order.rb
Hi Team,
This PR adds feature to  redesignate item to same order again.
Jira Ticket:- https://jira.crossroads.org.hk/browse/GCW-1935
=> GCW:1955 redesignate cancelled orders-pacakge

spec/controllers/api/v1/orders_packages_controller_spec.rb
Hi,
This is PR of test cases for 'GCW-1937- Remove orders_package from Order in draft state after deleting'.
Thanks
=> test case added for orders_package delete

spec/controllers/api/v1/orders_controller_spec.rb
Hi,
This is PR for GCW-1939 offline cart merging with draft order
Thanks
=> GCW 1939 offline cart merging draft order

spec/factories/orders.rb, spec/models/order_spec.rb, spec/rails_helper.rb, spec/serializers/api/v1/order_serializer_spec.rb
Hi Team,
This PR contains test cases for order state transitions. Please review and let me know if any changes required.
Thanks.
=> Gcw 1947 test cases for order workflow

app/serializers/api/v1/organisation_without_order_serializer.rb, app/serializers/api/v1/organisations_user_serializer.rb, spec/serializers/api/v1/organisation_without_order_serializer_spec.rb
Hi Team,
This PR fixes Organisation serializer issue.
Jira Ticket:- https://jira.crossroads.org.hk/browse/GCW-1919
=> GCW-1919 Organisation name not displaying on Browse

app/controllers/api/v1/items_controller.rb, app/models/organisations_user.rb, app/services/twilio_service.rb, config/locales/en.yml, config/locales/zh-tw.yml
Hi Team, 
This PR is to change sms text which is sent if any user is added to organisation from stock app. (i.e manage charity users feature).
https://jira.crossroads.org.hk/browse/GCW-2013
Previous text : Nokia from crossroads has added you to the GoodCity for Charities platform. Please download the app and log in using this mobile number.
New text : Nokia  has added you to the GoodCity for Charities platform. Please download the app and log in using this mobile number.
Thanks.
=> #July2018Release1

app/models/order.rb, app/services/twilio_service.rb, config/locales/en.yml, config/locales/zh-tw.yml
Hi Team,
This PR adds feature of sending sms notification to user whenever any order is submitted on Browse App.
Jira Ticket:- https://jira.crossroads.org.hk/browse/GCW-2045
Please review it and let me know if any changes are required.
thanks
=> GCW-2045 Order submission message

config/schedule.rb, lib/tasks/import_swd_organisations.rake
Hi Team,
In this PR we have uncommented swd organisation rake which we commented before to test capastrino crone jobs settings.
Thanks.
=> uncommented rake task script for deployment

db/migrate/20180723112054_change_gih3_id_column_type_to_string.rb, db/schema.rb, lib/tasks/import_swd_organisations.rake
Hi Team,
This PR Contains following changes:
- Fix for rollbar issue: https://rollbar.com/crossroads_it/api.goodcity/items/130/
- Changed column type of gih3_id to string to save same id as present in csv.
- Fixed issue: all values were getting assigned to single column name_en in comma separated manner where as values should be assign to appropriate columns.
Please review and let me know in case of any changes.
Thanks.
=> Fix issue: data not getting assigned properly

lib/tasks/import_swd_organisations.rake
Hi Team,
This PR is to assign district_id to organisation while executing swd rake.
Please review and let me know in case of any changes.
Thanks.
=> add csv and db district mapping and accordingly assign district_id

app/controllers/api/v1/orders_controller.rb, app/controllers/api/v1/territories_controller.rb, app/models/concerns/cacheable_json.rb, app/serializers/api/v1/address_serializer.rb, app/serializers/api/v1/district_serializer.rb, app/serializers/api/v1/territory_without_district_serializer.rb
Hi Team,
This PR adds Address detail for GGV transport on GGV page of Orders detail page.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2086
please review it and let me know if any further changes are required.
Thanks
=> GCW 2086 add address to ggv order detail page

app/controllers/api/v1/orders_controller.rb, app/controllers/api/v1/territories_controller.rb, app/models/order.rb, app/serializers/api/v1/address_serializer.rb, app/serializers/api/v1/district_serializer.rb, app/serializers/api/v1/order_serializer.rb, app/serializers/api/v1/territory_without_district_serializer.rb, spec/serializers/api/v1/order_serializer_spec.rb
Hi Team,
This PR contains changes for : 
- Add contact details on order details page of stock app (GCW-2055)
- Add district details for order. (GCW-2086)
Please review.
Thanks.
=> #Aug2018Release1

app/controllers/api/v1/items_controller.rb, app/controllers/api/v1/packages_controller.rb, app/jobs/stockit_update_job.rb, app/models/item.rb, app/models/package.rb, app/services/stockit/item_sync.rb, spec/jobs/stockit_update_job_spec.rb, spec/models/package_spec.rb, spec/services/stockit/item_sync_spec.rb
Hi Team,
This PR is to allow multi quantity sync from admin when package received from admin with inventory number.
https://jira.crossroads.org.hk/browse/GCW-1917
Please review and let me know in case of any changes.
Thanks.
=> Gcw 1917 allow multi quantity sync from admin

app/models/order.rb, spec/controllers/api/v1/orders_controller_spec.rb
Hi Team
This is PR for JIRA ticket GCW-2000- Remove draft order from search result.
https://jira.crossroads.org.hk/browse/GCW-2000
I have added scope to filter orders in draft state. 
Please review it and let me know if any change is required.
Thanks.
=> scope added for filtering orders in draft state

Gemfile.lock
A flaw in FFI has been resolved.
=> Fixed CVE-2018-1000201.

app/controllers/api/v1/orders_controller.rb, app/models/order.rb, spec/controllers/api/v1/orders_controller_spec.rb
Changes  : 
- Addition of tests for existing api pagination
- Orders search is now extended to descriptions, organisations, user names
- Orders search is now case insensitive
=> GCW 2119 improvements for orders search (aka designations)

app/controllers/api/v1/organisations_users_controller.rb, app/models/organisations_user.rb, config/locales/en.yml, config/locales/zh-tw.yml, lib/classes/organisations_user_builder.rb, spec/controllers/api/v1/organisations_user_controller_spec.rb, spec/lib/classes/organisations_user_builder_spec.rb, spec/models/organisations_user_spec.rb
Hi Team,
This is PR for jira ticket GCW-2069- Cannot assign NGO staffs who are registered in the donor app as a charity user.
https://jira.crossroads.org.hk/browse/GCW-2069.
I have covered all the possible scenarios.
Please review the code and let me know if any change is required.
Thanks
@steveyken @namrataukirde @Darshan-Chauhan
=> Gcw 2069 add ngo user as charity user

app/serializers/api/v1/order_serializer.rb, app/serializers/api/v1/stockit_local_order_serializer.rb, app/serializers/api/v1/user_profile_serializer.rb
This PR fixes code climate issues for serializers
=> CodeClimate fixes

app/models/permission.rb
Hi Team ,
This PR fixes code-climate indentation issue.
Thanks.
=> fix spacing issue

app/controllers/api/v1/gc_organisations_controller.rb, app/controllers/api/v1/images_controller.rb, app/controllers/api/v1/items_controller.rb, app/controllers/api/v1/locations_controller.rb
This PR fixes code climate issues for controllers
=> Code climate fixes for controllers

app/models/image.rb, app/models/offer.rb, app/models/orders_package.rb, app/models/package.rb
This PR fixes codeclimate issues for some models
=> CodeClimate fixes for models

app/controllers/api/v1/beneficiaries_controller.rb, app/controllers/api/v1/identity_types_controller.rb, app/controllers/api/v1/orders_controller.rb, app/models/ability.rb, app/models/beneficiary.rb, app/models/identity_type.rb, app/models/order.rb, app/serializers/api/v1/beneficiary_serializer.rb, app/serializers/api/v1/identity_type_serializer.rb, app/serializers/api/v1/order_serializer.rb, config/routes.rb, db/identity_types.yml, db/migrate/20180928023953_create_identity_types.rb, db/migrate/20180928031017_create_beneficiaries.rb, db/migrate/20181003055950_add_beneficiary_to_orders.rb, db/schema.rb, lib/tasks/identity_types.rake, spec/controllers/api/v1/beneficiaries_controller_spec.rb, spec/controllers/api/v1/identity_types_controller_spec.rb, spec/controllers/api/v1/orders_controller_spec.rb, spec/factories/beneficiaries.rb, spec/factories/identity_types.rb, spec/factories/orders.rb, spec/factories/sequences.rb, spec/models/beneficiary_spec.rb, spec/models/identity_type_spec.rb, spec/models/order_spec.rb
A beneficiary refers to the person the goods are meant to go to.
This PR includes the following changes : 
- Creation of an IdentityType model and endpoint
This is a lookup table for the different kinds of identification papers a person can have (e.g id card, passport, refugee form)
**NOTE**: A rake task has been added to populate the different types of IDs
- Creation of a Beneficiary model and endpoint
This model contains the details of a person : name, phone, id type/number
- Addition of a 'beneficiary' field to orders
=> GCW-2139 Beneficiary endpoint

app/controllers/api/v1/authentication_controller.rb, app/models/user.rb, app/services/twilio_service.rb, config/locales/en.yml, config/locales/zh-tw.yml, spec/controllers/api/v1/authentication_controller_spec.rb, spec/models/user_spec.rb, spec/services/twilio_service_spec.rb
Hi Team,
This PR contains changes for sending different login sms for browse app users as mentioned in ticket: https://jira.crossroads.org.hk/browse/GCW-2070
Please review and let me know in case of any changes. 
Thanks.
=> Gcw 2070 fix login pin conent for browse

app/controllers/api/v1/orders_controller.rb, app/models/order.rb, app/serializers/api/v1/order_serializer.rb, app/serializers/api/v1/order_shallow_serializer.rb, db/migrate/20181016071437_add_address_to_orders.rb, db/schema.rb, spec/controllers/api/v1/orders_controller_spec.rb, spec/models/order_spec.rb
=> GCW-2014 Add an address reference to an order

app/serializers/api/v1/browse_package_serializer.rb, spec/serializers/api/v1/browse_package_serializer_spec.rb
Hi Team,
This is PR for JIRA ticket GCW-2153- displaying inventory number in browse app.
https://jira.crossroads.org.hk/browse/GCW-2153.
I have added inventory_number in serializer in browse_package_serializer and also added specs for the same.
Please review it and let me know if any change is required.
Thanks.
=> GCW-2153 adding inventory number in serializer

config/locales/zh-tw.yml
Hi Team,
This is PR for Chinese translation of SMS pin message.
https://jira.crossroads.org.hk/browse/GCW-2070.
Please review it and let me know if any change is required.
Thanks
=> Fix: chinese translation added for sms pin message

app/controllers/api/v1/packages_controller.rb, app/models/ability.rb, app/models/package.rb, config/locales/en.yml, config/locales/zh-tw.yml, config/routes.rb, spec/controllers/api/v1/packages_controller_spec.rb
Hi Team,
This PR contains following changes
- Adds package quantity splitting features
- Adds Q inventory number feature for copying items
- Turns on ability to view quantity items
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2190
Please review and let me know if any other changes are required.
Thanks
**Note**: Test cases will be covered by @abhinav098 .
=> Split quantity feature

app/jobs/stockit_update_job.rb, app/models/package.rb, app/services/stockit/item_sync.rb, spec/jobs/stockit_update_job_spec.rb, spec/models/package_spec.rb, spec/services/stockit/item_sync_spec.rb
Hi Team,
This PR enables sync of quantity items for only create and update.
Please take a look and let me know if further changes are required.
Thanks
=> GCW-2197 Enable quantity item sync

app/models/package.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/migrations/change_order_transport_scheduled_at_to_datetime_spec.rb
=> Search items by case number

app/models/order.rb, spec/models/order_spec.rb
The rules we're trying to match are described here : https://jira.crossroads.org.hk/browse/GCW-2193
=> GCW-2193 Order priority rules

app/models/order.rb
Hi Team,
This PR fixes issue of orders_packages getting created with null entries.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2223
Please review it and let me know in further changes are required.
Thanks
=> GCW-2223 OrdersPacakges with null entries

app/models/ability.rb, db/permissions_roles.yml
Hi Team,
This PR makes calendar end point available to all users.
Thanks.
=> make calendar available to all users

db/migrate/20181207070950_add_missing_indexes.rb
On my development machine, the OfferSerializer goes from 47 secs to 21 seconds after running this code
=> Add missing indexes

app/controllers/api/v1/orders_controller.rb, app/serializers/api/v1/order_serializer.rb, app/serializers/api/v1/order_shallow_serializer.rb, db/migrate/20181212060849_add_column_to_orders.rb, db/structure.sql, spec/models/order_spec.rb
Hi Team,
This PR adds feature of modification and cancel of Order.
Jira ticket: https://jira.crossroads.org.hk/browse/GCW-2243
Please review it and let me know if further changes are required.
Thanks
=> GCW-2243 Order modification

app/models/order.rb, spec/models/order_spec.rb
Hi Team,
This is PR for GCW-2216- Recent Order. This PR covers all scenarios and specs for ordering of top 5 recent orders logged in user has worked on.
Thanks
=> Gcw 2216 recent order

app/controllers/api/v1/orders_controller.rb, app/serializers/api/v1/order_shallow_serializer.rb, app/serializers/api/v1/purpose_serializer.rb, db/migrate/20181224103318_add_order_type_to_order.rb, db/migrate/20181224131147_add_identifier_to_purpose.rb, db/purposes.yml, db/schema.rb, lib/tasks/purposes.rake, spec/factories/purpose.rb, spec/models/order_spec.rb, spec/serializers/api/v1/purpose_serializer_spec.rb
Hi Team,
This PR handles draft order scenario's for browse appointment feature.
https://jira.crossroads.org.hk/browse/GCW-2247
Please review.
Thanks
=> Gcw 2247 draft order fix

app/controllers/api/v1/orders_controller.rb, app/controllers/api/v1/packages_controller.rb, app/models/concerns/package_filtering.rb, app/models/package.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/factories/orders_packages.rb, spec/models/concerns/package_filtering_spec.rb
Hi team, 
This PR contains the API changes for filtering out items based on states, images, publish status. 
Please review and comment.
Thanks
=> GCW-2245 items filter api

app/models/concerns/package_filtering.rb
Hi Team, 
This PR fixes returning multiple items with same details. Please review and comment.
Thanks
=> Item filter => return uniq packages

app/models/appointment_slot.rb, app/models/booking_type.rb, app/models/concerns/order_filtering.rb, app/models/order.rb, app/models/order_transport.rb, app/serializers/api/v1/order_serializer.rb, app/serializers/api/v1/order_shallow_serializer.rb, app/serializers/api/v1/order_transport_serializer.rb, db/migrate/20190110123923_add_booking_type_id_to_orders.rb, db/schema.rb, lib/tasks/copy_booking_type.rake, spec/controllers/api/v1/appointment_slots_controller_spec.rb, spec/controllers/api/v1/orders_controller_spec.rb, spec/factories/order_transports.rb, spec/factories/orders.rb, spec/models/booking_type_spec.rb, spec/models/order_spec.rb, spec/models/order_transport_spec.rb
Hi team, this PR adds booking_type_id column to orders and changes related to that, in the serialisers.
Please review and comment.
Thanks
=> GCW-2286 edit booking type associations and make changes to serializers

app/controllers/api/v1/orders_controller.rb
Hi Team,
This PR permits booking_type_id for order creation.
Please review.
Thanks.
=> permit booking_type param for orders

app/controllers/api/v1/orders_controller.rb, app/controllers/api/v1/organisations_users_controller.rb, app/controllers/api/v1/users_controller.rb, app/models/ability.rb, app/models/order.rb, app/models/user.rb, app/serializers/api/v1/goodcity_request_serializer.rb, app/serializers/api/v1/user_serializer.rb, config/routes.rb, db/migrate/20190109072211_add_authorised_by_id_to_orders.rb, db/schema.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/models/user_spec.rb
Hi Team,
This is PR for Order Creation on Stock app on Charity User behalf.
This PR includes:
* search logic for searching User.
* Recent User for Search User page.
* Show action for Organisations User.
* Organisations User in Users serializer
* Specs for above cases.
=> Gcw 2246 staff can create order on users behalf

app/controllers/api/v1/offers_controller.rb, app/serializers/api/v1/package_serializer.rb
Hi Team,
This PR fixes issue of loading orders_packages with offers.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2249
Please review.
Thanks
=> GCW-2249 Avoid loading OrdersPackages for offers

app/models/concerns/order_filtering.rb
Hi Team,
This is fix for duplicate order search. Please review the PR and let me know if anything is required. 
Thanks.
=> FIX=>order search duplication fix added

app/models/concerns/message_subscription.rb, app/models/message.rb, app/models/offer.rb, app/models/order.rb
=> Gcw 2335 basic setup required for chat refactor messages

app/controllers/api/v1/orders_controller.rb, app/serializers/api/v1/order_shallow_serializer.rb, db/migrate/20190124105020_remove_order_type_column_from_order.rb, db/schema.rb, spec/models/order_spec.rb
Hi Team,
This PR removes order_type column from order. 
Please review.
Thanks.
=> Gcw 2348 remove order type column from order

lib/tasks/assign_online_order_booking_type_to_existing_goodcity_orders.rake
Hi Team,
This PR contains rake to assign online-order booking_type to existing goodcity order which exist before adding appointment feature.
Please review.
Thanks.
=> Gcw 2346 add online order booking type to existing goodcity orders

app/controllers/api/v1/orders_controller.rb, app/models/order.rb, spec/factories/orders.rb, spec/models/order_spec.rb
Hi Team,
This is PR for JIRA ticket GCW-2342- excluding authorised draft orders from my_orders page. https://jira.crossroads.org.hk/browse/GCW-2342. 
PR includes change in query and test cases for my_orders list. Please review the PR and let me know if any change is required.
=> Gcw 2342- exclude authorised draft order

app/controllers/api/v1/package_types_controller.rb, lib/tasks/stockit_codes.rake
@namrataukirde @Darshan-Chauhan We need this in order to pass GCW-2239
=> Need allow_request in params.

app/models/concerns/order_filtering.rb, spec/controllers/api/v1/orders_controller_spec.rb
Hi Team,
This PR contains changes for using "Online order" & "Appointment" universally.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2364
Please review and let me know.
Thanks
=> GCW-2364 modify online order filtering

.circleci/config.yml, app/controllers/api/v1/packages_controller.rb, app/models/concerns/package_filtering.rb, app/models/package.rb, db/migrate/20190129073952_add_indexes_to_package.rb, db/migrate/20190129081612_add_indexes_on_location.rb, db/migrate/20190131083340_add_indexes_to_packages_locations.rb, db/schema.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/models/concerns/package_filtering_spec.rb
This is the live release branch for GCW 2370 API performance updates
=> Gcw 2370 api performance live

app/controllers/api/v1/orders_controller.rb, app/models/order.rb, app/models/user.rb, app/services/twilio_service.rb, lib/tasks/copy_authorised_by_id.rake, spec/models/order_spec.rb
HI Team,
This PR contains changes for replacing authorised_by_id with submitted_by_id.
Please review.
Thanks.
=> Gcw 2349 replace authorised by id with submitted by

app/controllers/api/v1/orders_controller.rb, app/serializers/api/v1/order_shallow_serializer.rb, db/migrate/20190218025723_add_staff_note_to_orders.rb, db/schema.rb, spec/controllers/api/v1/holidays_controller_spec.rb, spec/controllers/api/v1/orders_controller_spec.rb, spec/models/order_spec.rb, spec/serializers/api/v1/order_serializer_spec.rb
This is field is meant to be used for the sticky note on the logisitics tab
As seen here: https://xd.adobe.com/view/224f7314-f1c0-40b6-7d7a-929e616be6bb-547e/screen/2f427e12-2183-4a74-869b-eb3d62c8d5e8/iPhone-6-7-8-97/
=> GCW-2366 Add staff note to order

app/models/user.rb, db/migrate/20190214025513_add_indexes_to_subscriptions.rb, db/schema.rb
This is a cleaner copy of  #648
=> Add indexes to subscriptions

app/controllers/api/v1/authentication_controller.rb
https://rollbar.com/crossroads_it/api.goodcity/items/230/
=> GCW-2335 current_user_channels fix

app/controllers/api/v1/organisations_users_controller.rb, app/models/user.rb, db/migrate/20190227162128_remove_uniq_index_constraint_for_user_mobile.rb, db/schema.rb, lib/classes/organisations_user_builder.rb, spec/controllers/api/v1/authentication_controller_spec.rb, spec/lib/classes/organisations_user_builder_spec.rb, spec/models/user_spec.rb
Hi Team,
This PR contains changes for making mobile field optional while creating a user from the stock app.
Please review.
Thanks.
=> Gcw 2433 make mobile field optional for stock

app/models/message.rb, spec/models/message_spec.rb
Hello team, 
This PR adds validation to message model for checking body's presence.
Thanks
=> GCW-2425 add validation to message model

app/controllers/api/v1/messages_controller.rb, app/models/message.rb
Hi team please review this, PR for read/unread count
=> GCW-2414 mark messages read

app/models/order.rb, db/migrate/20190308142745_remove_authorised_by_id_from_order.rb, db/schema.rb, spec/models/order_spec.rb
Hi Team,
This PR removed an authorised_by_id column from order.
Please review.
Thanks.
=> Gcw 2379 remove authorised by id column from order

app/controllers/api/v1/messages_controller.rb, app/models/message.rb, app/serializers/api/v1/message_serializer.rb, spec/controllers/api/v1/messages_controller_spec.rb, spec/models/message_spec.rb
- Allow the endpoint to support multiple order_ids / item_ids / order_ids e.g `GET /messages?order_id=123,654,789`
- Allow fetching the user's message by state e.g `GET /messages?order_id=123,654,789&state=unread`
=> Fetch messages by state

app/controllers/api/v1/users_controller.rb, app/models/concerns/user_search.rb, app/models/user.rb, spec/models/user_spec.rb
Hi team, in this PR. 
For user-search, search includes email and mobile
=> GCW-2480 Search user improvements

spec/services/push_service_spec.rb
This PR is for fixing failing specs, for the following commit
https://github.com/crossroads/api.goodcity/pull/681/commits/cf62ebfd4263ba03810409f2e6ad94cec1875fa6
=> fix failing specs

app/models/concerns/push_updates_for_subscription.rb
Send order id in the notification as well.
=> fix blank message notification for stock

lib/classes/organisations_user_builder.rb
Hi Team,
This PR fixes issue of `OrganisationUserBuilder` bypassing validation for `User`.
Ticket:- https://jira.crossroads.org.hk/browse/GCW-2485
Please review
=> GCW-2485 User uniq email issue

app/controllers/api/v1/gc_organisations_controller.rb, app/controllers/api/v1/users_controller.rb, spec/controllers/api/v1/gc_organisations_controller_spec.rb, spec/controllers/api/v1/users_controller_spec.rb
Hello team this PR contains changes mentioned here
https://jira.crossroads.org.hk/browse/GCW-2480?focusedCommentId=33597&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-33597.
Thanks
=> GCW-2480 Limit user and organisations search to 25 records

app/models/order.rb, app/models/user.rb, app/services/sendgrid_service.rb, spec/models/order_spec.rb, spec/services/sendgrid_service_spec.rb, spec/services/twilio_service_spec.rb
As titled. Could you guys check the specs, make sure I got the rules correctly ?
=> Appointment confirmation emails

app/controllers/api/v1/authentication_controller.rb, app/models/user.rb, app/serializers/api/v1/user_profile_serializer.rb, db/migrate/20190401073134_add_verified_fields_to_user.rb, db/schema.rb, spec/controllers/api/v1/authentication_controller_spec.rb, spec/models/user_spec.rb
Hi Team,
This PR introduces the verified flag for email and mobile.
Please review.
Thanks
=> GCW-2479 add verified flag for mobile and email

app/models/user.rb
Hi team, This PR removes the restriction for fake_email on staging. Please review
THanks
=> enable tools like mailinator on staging

app/models/user.rb
Hello team this PR fixes validation issues for user mobile and email.
Thanks
=> Fixing email and mobile validations check uniqueness if values present

app/controllers/api/v1/orders_controller.rb, app/models/concerns/order_filtering.rb
The serializers exploded, so I'm moving to a sorting post-query
This will be replaced once we implement Matt's sorting design later on
No changes on the tests as the expected behaviour did not change
will merge for Matt to be able to test on Staging. Please review post-merge. Thanks :D
=> Fix distinct issue by sorting after sql

app/controllers/api/v1/packages_controller.rb, app/models/order.rb, config/locales/en.yml, config/locales/zh-tw.yml, spec/controllers/api/v1/packages_controller_spec.rb, spec/models/order_spec.rb
Hi team,
This PR add api side restriction for item dispatch(partial)
Thanks
=> GCW-2394 dont allow item dispatch if order not processed

app/services/sendgrid_service.rb, app/services/twilio_service.rb
This PR fixes the slack sms.
Thanks
=> Fix blank sms issue for slack sms.

lib/classes/designator.rb, spec/lib/classes/designator_spec.rb
Hi Team, 
This PR has changes regarding removal of quantity assignment on API side and issue regarding quantity update after redesignating.
Thanks
=> FIX=> remove undesignate quantity assignment

app/services/twilio_service.rb
Fix For this message
SlackSMS ()  has added you to the GoodCity for Charities platform. Please download the app and log in using this mobile number.
Thanks.
=> Stop blank message if there's no user 

app/serializers/api/v1/organisations_user_serializer.rb, spec/factories/organisations_users.rb, spec/factories/sequences.rb, spec/serializers/api/v1/organisations_user_serializer_spec.rb
Hi Team,
This PR is to add preferred_contact_number to organisations_user serializer.
Please review.
Thanks.
=> fix mobile number not getting saved up on sign-up using email

app/services/sendgrid_service.rb
Hi Team,
This PR adds bcc for appointment email and changes from email id for same.
Please review.
Thanks
=> bcc appointment email to staff and change from email id for booking

app/services/sendgrid_service.rb
- Add BCC for appointment emails and change from email
=> #April2019Release2

app/controllers/api/v1/orders_controller.rb, app/models/concerns/order_filtering.rb, spec/controllers/api/v1/orders_controller_spec.rb
As titled. This is a requirement for https://jira.crossroads.org.hk/browse/GCW-2503
=> Filter orders by due date

Gemfile.lock, app/controllers/api/v1/authentication_controller.rb, app/models/user.rb, app/serializers/api/v1/organisations_user_serializer.rb, app/serializers/api/v1/user_profile_serializer.rb, db/migrate/20190401073134_add_verified_fields_to_user.rb, db/schema.rb, spec/controllers/api/v1/authentication_controller_spec.rb, spec/factories/organisations_users.rb, spec/factories/sequences.rb, spec/models/user_spec.rb, spec/serializers/api/v1/organisations_user_serializer_spec.rb
Hi Team,
This PR contains changes for:
- Add verified flag.
- Add preferred contact number.
Please review.
Thanks.
=> #April2019Release3: Email related fixes

app/models/concerns/push_updates.rb, app/models/goodcity_request.rb, app/models/order_transport.rb, app/services/channel.rb, spec/controllers/api/v1/authentication_controller_spec.rb, spec/models/order_transport_spec.rb, spec/services/channel_spec.rb
This PR fixes the issue @abhinav098 reported where popups would appear on Admin whenever an order was submitted
=> Fix wrong order channel definition

app/controllers/api/v1/orders_controller.rb, app/models/concerns/order_filtering.rb, app/models/order.rb, spec/models/order_spec.rb
Use SQL to order search results by scheduled_at date
=> Using SQL to sort order search results.

app/services/package_splitter.rb, spec/services/package_splitter_spec.rb
[WIP] - rake task is pending for existing data.
Fix a minor bug, where received quantity was not getting decremented for original package.
Thanks
Live-support issue mentioned here https://crossroads-hk.slack.com/archives/CC1J20Z42/p1556854683041400
=> Decrease received quantity in original package

app/controllers/api/v1/orders_controller.rb
Hi Team,
I have added pagination for orders index action according to passed per_page params.
Thanks
=> GCW-2555-Add pagination according to params

lib/classes/organisations_user_builder.rb, spec/lib/classes/organisations_user_builder_spec.rb
Hi Team,
This PR contains changes for an organisations_user record will be created only if user is created.
Please review.
Thanks.
=> fix account details page submission if mobile number is not present

lib/classes/organisations_user_builder.rb, spec/lib/classes/organisations_user_builder_spec.rb
Hi Team,
This PR fixes issue of organisations_user was getting created even if user was not saved to db.
Please review.
Thanks.
=> #May2019Release2

.circleci/config.yml, app/controllers/api/v1/authentication_controller.rb
Changes to register device with fcm
=> Make changes to the API for using fcm instead of GCM

app/controllers/api/v1/organisations_users_controller.rb, lib/classes/organisations_user_builder.rb, spec/lib/classes/organisations_user_builder_spec.rb
Hi Team,
Fix to account details update throws `mobile number invalid` error.
Please review.
Thanks.
=> #May2019Release4

app/controllers/api/v1/packages_controller.rb, app/models/orders_package.rb, lib/classes/designator.rb, spec/lib/classes/designator_spec.rb
Hi Team,
This PR is for JIRA ticket GCW-2577 (https://jira.crossroads.org.hk/browse/GCW-2577). I have added change for updating cancelled orders package in orders and also added new specs and some minor changes for it. Please review the PR and let me know if any change is required.
=> GCW- 2577- updating cancelled Orders Packages

app/controllers/api/v1/organisations_users_controller.rb, lib/classes/organisations_user_builder.rb, spec/lib/classes/organisations_user_builder_spec.rb
Hi Team,
This PR adds app_name to initialize method instead of passing it to each and every method. 
Please review.
Thanks.
=> Added app to initialise instead of passing to each method.

app/controllers/api/v1/packages_controller.rb, app/models/concerns/package_filtering.rb, app/models/package.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/models/package_spec.rb
Hi Team,
This PR is for handling multi quantity filter on Api side instead of stock app side. I have added params to filter for Orders page Item search. Please review the PR and let me know if any change is required. 
Thanks
=> FIX=> Handling multiquantity filter on api side

db/migrate/20190614084520_add_indexes_to_offer.rb, db/migrate/20190614084726_add_indexes_to_user.rb, db/migrate/20190614084900_add_indexes_to_order.rb, db/schema.rb
Crazy to think we're missing some of these indexes. Adding these will speed up numerous queries and give us a performance boost.
=> Add more indexes

app/controllers/api/v1/api_controller.rb, app/controllers/api/v1/offers_controller.rb, app/controllers/api/v1/orders_controller.rb, app/models/concerns/offer_filtering.rb, app/models/concerns/offer_search.rb, app/models/offer.rb, spec/controllers/api/v1/offers_controller_spec.rb, spec/models/concerns/offer_search_spec.rb
Hi Team,
This PR is for ticket GCW-26666- Filter UI for searching offers. Please review the PR and let me know if any change is required.
=> GCW- 2666: Provide filters for offer search

spec/controllers/api/v1/offers_controller_spec.rb
Hi Team,
This PR is fix for random failing specs of offers filters PR. Please review this PR and let me know if any change  is required.
**Note**: There still need some improvement in specs will do this change once Filter feature is on staging.
=> FIX => Failing specs on master for offers_filters

app/models/booking_type.rb, app/models/order.rb, app/models/order_transport.rb, app/services/sendgrid_service.rb, spec/models/order_spec.rb, spec/models/order_transport_spec.rb, spec/services/sendgrid_service_spec.rb
Hello team,
This PR is for sending emails to the users on order submission for pickup and delivery.
Please review.
Thanks
Will need to add template ids to the .env file for staging and prod both.
=> GCW-2605 send submission email

app/models/ability.rb
Fix Incorrectly scoped package permissions
=> fix package permission

app/models/order.rb, app/serializers/api/v1/orders_package_serializer.rb, config/locales/en.yml, config/locales/zh-tw.yml, lib/classes/cart_checkout.rb, spec/controllers/api/v1/requested_packages_controller_spec.rb
Hi Team,
This PR is for JIRA ticket GCW-2683- Allow to add items to submitted orders. Please review this PR and let me know if any change is required.
=> GCW-2683-Allow to add items to submitted order

lib/tasks/set_publish_status_for_package.rake
This PR is a rake task to set publishing status of packages based on location. 
Please review it. 
To run this rake task run the following command.
`rake 'goodcity:set_publish_status_for_package[location_name, status]'`
`rake 'goodcity:set_publish_status_for_package[xyz, true]'`
=> set publish status for packages

app/models/booking_type.rb, app/models/order.rb, app/services/sendgrid_service.rb, spec/factories/orders.rb, spec/models/order_spec.rb, spec/services/sendgrid_service_spec.rb
An email sent when an online order finishes processing
=> GCW-2678 Online order confirmation mail

app/controllers/api/v1/offers_controller.rb, app/models/ability.rb, app/models/concerns/offer_filtering.rb, app/models/concerns/offer_search.rb, app/models/offer.rb, config/routes.rb, spec/controllers/api/v1/offers_controller_spec.rb
Hi Team,
This PR is for ticket GCW-2685- Admin Dashboard. This PR includes:
1) Offers count Active States for All Offers and logged in User. I have added separate endpoint 'summary' for this.
2) Recent Offers query for fetching recent 5 Offers according state (it will be 'submitted' in this case).
3) Removed 'draft' Offers in search and filter query.
4) Test cases for Recent Offers and Offers summary (Offers Count).
=> GCW-2685- Admin Dashboard

app/models/image.rb, lib/tasks/handle_heic_images.rake, spec/models/image_spec.rb
Hello Team, 
This PR handles the heic images coming from new iphones.
Please review
Thanks
=> GCW-2690 handle heic images and add a rake for fixing old images

app/controllers/api/v1/companies_controller.rb, app/models/company.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/models/company_spec.rb
Earlier, we didn't had any validations for company name, so added those to company. 
Please review
Thanks.
=> Add validation to company name

app/controllers/api/v1/api_controller.rb, spec/controllers/api/v1/organisations_user_controller_spec.rb, spec/controllers/api/v1/requested_packages_controller_spec.rb
Send errors in response properly mapped to keys.
=> Gcw 2763 handle errors graciously

app/controllers/api/v1/packages_controller.rb, app/models/package.rb, app/serializers/api/v1/package_serializer.rb, app/serializers/api/v1/package_type_serializer.rb, app/serializers/api/v1/stockit_item_serializer.rb, app/services/stockit/item_sync.rb, db/migrate/20190911061558_add_weight_and_pieces_to_packages.rb, db/migrate/20190917110924_add_allow_pieces_to_package_types.rb, db/schema.rb, spec/factories/packages.rb, spec/models/package_spec.rb, spec/models/package_type_spec.rb, spec/serializers/api/v1/package_serializer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-2780
FEATURE: Adds weight and pieces columns to packages table with live sync to stockit.
Stock Item creation.
=> GCW-2780 add weight and pieces with sync functionality to stockit

app/controllers/api/v1/companies_controller.rb
https://jira.crossroads.org.hk/browse/GCW-2691
BUG: show actual error for company controller instead of something went wrong
Company creation page for corporate donor.
=> use save with errors method

db/package_categories_package_type.yml, lib/classes/package_category_importer.rb, lib/tasks/package_types.rake
Simple seeding data update + specific rake task
Note: changes are in the yaml file
=> Update of package type/category mapping

db/package_categories_package_type.yml, lib/classes/package_category_importer.rb, lib/tasks/package_types.rake
https://jira.crossroads.org.hk/browse/GCW-2529
This is a cherry-pick of [THIS COMMIT](https://github.com/crossroads/api.goodcity/commit/f2332a85dcc93c04d22aaa526751f16ad1d012b0)
Update the `PackageType/PackageCategory` mapping to include new categories into the app.
This is mainly a YAML file update.
A rake task has been created but all it does is call existing code
- Browse Categories
- Stock item types
=> #Release:  Updated Package Mapping

lib/classes/package_category_importer.rb
Fix of a rake task done by @namrataukirde (thanks!)
=> Release: package mapping update

app/models/ability.rb, spec/controllers/api/v1/beneficiaries_controller_spec.rb
Users could not see beneficiaries that were created by someone else for their orders.
Will merge asap as this is a live issue
=> Fix beneficiary abilities

app/models/concerns/subform_utilities.rb, app/services/stockit/item_detail_sync.rb
BUG: Fixes sync issue for computer_accessory, and issues found while testing. 
Item Creation
=> Fix computer accessories sync issue

lib/tasks/create_lookups.rake
This PR fixes a typo in create lookup rake task.
=> NovemberRelease#3 

config/deploy/staging.rb, lib/tasks/create_lookups.rake
FIX => Twilio sms fix due to Twilio gem change.
Please review.
=> #November2019Release4

config/schedule.rb
FEATURE: Specify feature name
BUG: Specify bug 
NOTE: Give a description of what this PR does. If it fixes any bug, specify cause of an issue and approach/solution added to fix that issue.
NOTE: IF there is any conversation happened for current changes in any of the slack channel, mention the slack message link.
=> add 5 minutes as cron time scheduler for testing

lib/goodcity/compare/items.rb, lib/goodcity/create_stockit_package.rb
Some extra follow ups to the previous merge. Just scripts
=> Gcw 2858 data sanitization

app/controllers/api/v1/computer_accessories_controller.rb, app/controllers/api/v1/computers_controller.rb, app/controllers/api/v1/electricals_controller.rb, app/controllers/api/v1/packages_controller.rb, app/models/computer.rb, app/models/computer_accessory.rb, app/models/concerns/subform_utilities.rb, app/models/electrical.rb, app/services/stockit/item_detail_sync.rb, lib/classes/package_detail_builder.rb, spec/controllers/api/v1/computer_accessories_controller_spec.rb, spec/controllers/api/v1/computers_controller_spec.rb, spec/controllers/api/v1/electricals_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-2840
FEATURE: Additional fields editing package type for packages already created. There are different scenarios for subform is handled in this PR.
Package details page where user can edit existing subform to same/other/no subforms.
https://xd.adobe.com/view/224f7314-f1c0-40b6-7d7a-929e616be6bb-547e/screen/7d129040-9142-4ed1-ba71-8011197fae58/Create-Item-Computer-form/?x_product=xd-jiraserver/1.0
=> GCW-2840-Edit subform Feature

app/services/stockit/item_sync.rb
BUG: Hot fix where quantity numbers were not being correctly sync'd back to Stockit
GoodCity -> Stockit sync
=> Quantity sync fix

Gemfile.lock
This PR fixes rack vulnerability. Please review.
=> fix rack vulnerability

app/controllers/api/v1/offers_controller.rb, app/models/concerns/offer_filtering.rb, spec/controllers/api/v1/booking_types_controller_spec.rb, spec/controllers/api/v1/offers_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-2906
FEATURE: Adding Sorting feature on Offers list page
Offers list/search page
https://xd.adobe.com/view/224f7314-f1c0-40b6-7d7a-929e616be6bb-547e/screen/d9e55a7a-570f-4805-9224-93be92764702/iPhone-6-7-8-105?x_product=xd-jiraserver%2F1.0
=> GCW-2906-sorting offers

app/models/package.rb
Nothing Major, this PR moves out two methods out of private scope, so that they can be used outside the package class.
=> GCW-2774 move methods out of private

app/controllers/api/v1/orders_controller.rb, app/controllers/api/v1/orders_packages_controller.rb, spec/controllers/api/v1/orders_controller_spec.rb, spec/controllers/api/v1/orders_packages_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-2932
Added orders_packages count in index orders_packages index action
Please review.
=> FIX=> Adding orders_packages count in index orders_packages index action

app/controllers/api/v1/orders_packages_controller.rb
https://jira.crossroads.org.hk/browse/GCW-2932
Added sorting of orders_packages by its id.
=> FIX=> Sort orders_packages by id 

db/seeds.rb
https://jira.crossroads.org.hk/browse/GCW-2986
It adds missing seed data for goodcity_setting, lookup and storage_type tables.
Please review.
Thanks.
=> GCW-2986 add missing seed data

db/seeds.rb
https://jira.crossroads.org.hk/browse/GCW-2986
This PR adds locations to seed data.
Please Review.
Thanks.
=> GCW-2986 add missing location seed data

db/printers.yml, db/seeds.rb
Hi Team,
This PR adds printers data in DB seed.
Please review.
Thanks.
=> add printers in db seed

app/controllers/api/v1/packages_controller.rb
https://jira.crossroads.org.hk/browse/GCW-3006
Fixes Issue: Package update throws 422 if its already designated
Please Review.
Thanks.
=> GCW-3006 fix 422 for update of already designated packages

app/controllers/api/v1/packages_controller.rb, app/models/ability.rb, app/models/packages_inventory.rb, app/serializers/api/v1/stockit_item_serializer.rb, config/routes.rb
FEATURE: Specify feature name
BUG: Specify bug 
NOTE: Give a description of what this PR does. If it fixes any bug, specify cause of an issue and approach/solution added to fix that issue.
NOTE: IF there is any conversation happened for current changes in any of the slack channel, mention the slack message link.
=> Create separate endpoint for quantity

app/controllers/api/v1/packages_controller.rb, app/models/concerns/package_filtering.rb, spec/models/concerns/package_filtering_spec.rb
**This PR contains the following changes:** 
1. Minor Serializer fixes
2. item search fixes to restrict uninventorized items while searching anywhere in the app.
=> GCW-2859 fix item listing issue and send on hand quantity in the response

app/serializers/api/v1/package_serializer.rb
https://jira.crossroads.org.hk/browse/GCW-2985
update package serializer to send on-hand-quantity
Package serializer
=> GCW-2985 update package serializer to send on-hand-quantity

Gemfile, Gemfile.lock, app/controllers/api/v1/packages_controller.rb, app/models/concerns/package_filtering.rb, app/models/storage_type.rb
GCW-2859 https://jira.crossroads.org.hk/browse/GCW-2859
SUGGESTION: Items listed in item search should not contain boxes while adding for a box..
=> GCW-2859 fix minor suggestions and issues

app/models/concerns/operations/stock_operations.rb, app/models/package.rb, config/locales/en.yml, config/locales/zh-tw.yml, spec/controllers/api/v1/packages_controller_spec.rb, spec/models/concerns/operations/stock_operations_spec.rb, spec/models/package_spec.rb
NOTE: https://jira.crossroads.org.hk/browse/GCW-3044
BUG:  https://jira.crossroads.org.hk/browse/GCW-3044?focusedCommentId=37308&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-37308
Box/pallet item addition/removal screen.
=> GCW-3044 check on API for dispatched item before pack/unpack operations

Gemfile.lock, app/controllers/api/v1/packages_controller.rb, app/models/cancellation_reason.rb, spec/models/cancellation_reason_spec.rb
Added following changes =>
- Added condtion `where(nil)` for fetching all cancellation reason if no type matches and added specs related to it.
-  replaced `find` by `find_by` in packages_controller actions.
Please review
=> Change => added release requested changes

Gemfile.lock
Hi Team
This PR fixes `rake` vulnerability. 
=> FIX=> rake vulnerability

LICENSE
March2020 Release#2
This release contains the following fix: 
- GCW-3074-cancellation-reason-live-update-issue
- Rake vulnerability
=> March2020 Release#2

config/locales/zh-tw.yml
This PR adds translations for box pallet feature.
=> GCW-2859 add chinese translations for box/pallet feature

app/models/concerns/operations/stock_operations.rb, app/models/package.rb, app/models/packages_inventory.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/models/concerns/operations/stock_operations_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3087
Gan action for the packages.
=> GCW-3087 gain action for packages

lib/goodcity/package_setup.rb
This change allows us to run the rehearsal against PROD without releasing first.
=> Fix: rehearsal validates manually

app/serializers/api/v1/stockit_set_item_package_serializer.rb
Fixed package creation issue.
NOTE: IF there is any conversation happened for current changes in any of the slack channel, mention the slack message link.
=> Fixed creation of package

app/controllers/api/v1/twilio_inbound_controller.rb, app/controllers/concerns/twilio_config.rb, app/services/twilio_inbound_call_manager.rb, doc/twilio_setup.md
https://jira.crossroads.org.hk/browse/GCW-3075
fixed issue with twilio inbound calls
=> GCW-3075 fixed issue with twilio inbound calls

app/models/offer.rb
https://jira.crossroads.org.hk/browse/GCW-2722
Fixed issue with resubmission of offer added by admin
=> GCW-2722 fixed issue with resubmission of offer added by admin

lib/classes/cart_checkout.rb
Use a lock to handle race conditions on the cart checkout
=> Cart Checkout Race Condition

app/models/concerns/operations/order_fulfilment_operations.rb
A temporary workaround to get us through the next week. (this is terrible)
=> Dispatch: Skip state validation for StockIt

app/models/concerns/inventory_computer.rb, app/models/concerns/inventory_legacy_support.rb, app/models/concerns/operations/designation_operations.rb, app/models/concerns/operations/location_operations.rb, app/models/concerns/operations/order_fulfilment_operations.rb, app/models/concerns/operations/stock_operations.rb, app/models/concerns/secured.rb, app/models/package.rb, app/models/packages_inventory.rb, app/models/packages_location.rb, app/services/package_splitter.rb, config/database.yml, config/locales/en.yml, config/locales/zh-tw.yml, spec/controllers/api/v1/orders_controller_spec.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/factories/packages.rb, spec/models/concerns/operations/designation_operations_spec.rb, spec/models/package_spec.rb, spec/models/packages_inventory_spec.rb
As titled, the fix I added previously was incomplete.
=> Fix more concurrency issues

app/models/package.rb
https://jira.crossroads.org.hk/browse/GCW-2658
GCW-2658 avoid the creation of duplicate package images
=> GCW-2658 avoid creation of duplicate package images

app/models/order.rb, spec/controllers/api/v1/orders_controller_spec.rb, spec/factories/orders.rb, spec/models/order_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3108
This fixes the occurrence of https://rollbar.com/crossroads_it/api.goodcity/items/663/
=> Fix rollbar error for booking type

app/models/concerns/operations/order_fulfilment_operations.rb, app/serializers/api/v1/image_serializer.rb, spec/serializers/api/v1/image_serializer_spec.rb
=> Add imageable_{type|id} to image serializer

db/permissions_roles.yml, spec/controllers/api/v1/users_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3107
Updates the permission for Order Administrator
=> GCW-3107 Update permission for offer administrator

app/models/concerns/operations/order_fulfilment_operations.rb, app/serializers/api/v1/image_serializer.rb, spec/serializers/api/v1/image_serializer_spec.rb
This is required for the image fix
=> Release: Add imageable_{type|id} to image serializer

app/controllers/api/v1/orders_controller.rb, app/models/order.rb, spec/models/order_spec.rb
https://jira.crossroads.org.hk/browse/GCW-2926
To fix the copy and pasted number not to be allowed in the database . As mentioned in the comment https://jira.crossroads.org.hk/browse/GCW-2926?focusedCommentId=38067&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-38067
=> GCW-2926-Error message was not poping when no of people benefited was edited fix

app/controllers/api/v1/orders_packages_controller.rb, app/controllers/api/v1/orders_process_checklists_controller.rb, app/models/ability.rb, app/models/orders_process_checklist.rb, app/serializers/api/v1/orders_package_serializer.rb, app/serializers/api/v1/orders_process_checklists_serializer.rb, config/routes.rb, db/permissions_roles.yml, spec/factories/roles.rb, spec/factories/users.rb, spec/models/abilities/orders_process_checklists_abilities_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3109
fixed order update and fetch orders_process_checklists
=> GCW-3109 fixed order update and fetch orders_process_checklists

app/controllers/api/v1/packages_controller.rb, app/models/package.rb, app/serializers/api/v1/stockit_item_serializer.rb, spec/controllers/api/v1/packages_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3119
Adds saleable field in creating and edit section of item
https://github.com/crossroads/stock.goodcity/pull/705
=> GCW-3119 Add "Saleable" field to create / view / edit on packages

app/models/order.rb, spec/models/order_spec.rb
https://jira.crossroads.org.hk/browse/GCW-2926
Changed the value from greater than 1 to greater than 0
=> Changed value of people_helped from 1 to 0

app/controllers/api/medicals_controller.rb, app/controllers/api/v1/medicals_controller.rb, app/controllers/api/v1/packages_controller.rb, app/models/ability.rb, app/models/medical.rb, app/serializers/api/v1/medical_serializer.rb, config/routes.rb, db/medicals.yml, db/migrate/20200407095552_add_medical_subform.rb, db/schema.rb, lib/classes/package_detail_builder.rb, lib/tasks/create_dummy_package_details.rake, spec/controllers/api/v1/medicals_controller_spec.rb, spec/factories/countries.rb, spec/factories/medicals.rb, spec/models/medical_spec.rb, spec/serializers/api/v1/medical_serializer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3110
Adds subform for medical item type
https://github.com/crossroads/stock.goodcity/pull/693
=> GCW-3110 Adding Medical Subform

app/controllers/api/v1/beneficiaries_controller.rb, app/models/beneficiary.rb, spec/controllers/api/v1/beneficiaries_controller_spec.rb, spec/models/beneficiary_spec.rb
https://jira.crossroads.org.hk/browse/GCW-2401
Added Backend check for characters of firstname and lastname
=> Added validation check for first and last names

app/controllers/api/v1/beneficiaries_controller.rb, app/controllers/api/v1/orders_controller.rb, app/controllers/api/v1/packages_controller.rb, app/models/ability.rb, app/models/concerns/inventory_computer.rb, app/models/concerns/package_boxing.rb, app/models/package.rb, app/models/packages_inventory.rb, config/database.yml, config/routes.rb, db/schema.rb, spec/controllers/api/v1/orders_controller_spec.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/models/concerns/offer_search_spec.rb, spec/models/concerns/operations/designation_operations_spec.rb, spec/models/package_spec.rb, spec/models/packages_inventory_spec.rb, spec/rails_helper.rb
* Adds an endpoint to fetch the parent containers of a package
* Fix specs that are failing on Master
* Small refactor of existing box code
* Fix bugs that were hidden in specs
=> GCW-3104 - Fetch package containers

app/controllers/api/v1/medicals_controller.rb
https://jira.crossroads.org.hk/browse/GCW-3110
Fixes the apipe param check. And solves issue reported in the ticket
=> GCW-3110 Medical subform Fix apipe params

app/models/beneficiary.rb, spec/models/beneficiary_spec.rb
Change the length to fix the issue
=> Fixed rollbar breaking of benficiary

app/models/beneficiary.rb, spec/factories/beneficiaries.rb
=> Validation Changes

app/serializers/api/v1/package_serializer.rb, spec/serializers/api/v1/package_serializer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3119
Fixes the live update issue for the saleable field.
=> GCW-3119 Fix live update

app/controllers/api/v1/orders_process_checklists_controller.rb
Fixed rollbar error https://rollbar.com/crossroads_it/api.goodcity/items/3367/
=> fixed issue with loading orders_process_checklists

app/controllers/api/v1/packages_controller.rb
=> Add images to box endpoint

db/permissions_roles.yml, spec/controllers/api/v1/users_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3121
Gives permission for order fulfilment users to create new orders
=> GCW-3121 Add create order role for order-fulfilment users

app/controllers/api/v1/orders_controller.rb, app/models/concerns/order_filtering.rb, app/models/order.rb, app/serializers/api/v1/order_serializer.rb
https://jira.crossroads.org.hk/browse/GCW-3120
Changes to send messages related to orders.
https://github.com/crossroads/stock.goodcity/pull/708
=> GCW-3120 Send order-related messages

app/models/ability.rb, lib/tasks/add_permissions_for_roles.rake, lib/tasks/remove_extra_role_permissions.rake
https://jira.crossroads.org.hk/browse/GCW-3126
- Fixes the ability for charity user unable to delete the beneficiary
- Added rake task to delete the permissions
=> GCW-3126 Fix Unable to delete beneficiary

app/models/ability.rb
https://jira.crossroads.org.hk/browse/GCW-3126
Fixes the issue mentioned by Tim in the JIRA
=> GCW-3126  User cannot remove/add client to their own order

app/models/concerns/package_filtering.rb, app/models/package.rb, app/models/packages_inventory.rb, spec/factories/packages_inventories.rb, spec/models/concerns/package_filtering_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3105
Added query for Item filter for inventory actions along with specs.
=> GCW-3105-Enchanced item filters

app/controllers/api/v1/packages_controller.rb, app/models/concerns/valuation_calculator.rb, app/models/package.rb, app/serializers/api/v1/package_serializer.rb, app/serializers/api/v1/stockit_item_serializer.rb, config/routes.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/factories/package_types.rb, spec/factories/packages.rb, spec/models/concerns/valuation_calculator_spec.rb
https://jira.crossroads.org.hk/browse/GCW-2979
This also supports for https://jira.crossroads.org.hk/browse/GCW-3127
FEATURE: Adds to ability to calculate default valuations of packages based on their type, condition and grade.
This supports https://github.com/crossroads/stock.goodcity/pull/723
https://github.com/crossroads/api.goodcity/pull/994
=> GCW-2979 Package valuations - Controller and Model actions

app/models/package.rb, app/models/storage_type.rb, config/locales/en.yml, config/locales/zh-tw.yml, spec/models/package_spec.rb
Simple change to prevent boxes and pallets to be parts of set
=> GCW-3101 Prevent boxes in sets

app/controllers/api/v1/packages_controller.rb, app/serializers/api/v1/stockit_item_serializer.rb, app/services/stockit/item_sync.rb, db/migrate/20200610104052_add_comment_to_packages.rb, db/schema.rb, spec/serializers/api/v1/package_serializer_spec.rb
=> Add => Comment in Package model.

db/schema.rb
=> Fixing Schema

app/controllers/api/v1/messages_controller.rb, spec/controllers/api/v1/messages_controller_spec.rb
=> Fix backward compatibility for Browse requests

app/models/concerns/message_subscriptions.rb, app/models/message.rb, spec/models/concerns/message_subscriptions_spec.rb
This fixes messages issues encountered while testing
- Donor sends the message and there are no subscribers
- Paper trail for messageable
=> Fix Message subscription issue

app/controllers/api/v1/users_controller.rb
=> Add unique mentionable members

app/serializers/api/v1/user_mentions_serializer.rb, spec/controllers/api/v1/users_controller_spec.rb
=> Adding image in the mentions response

app/controllers/api/v1/packages_inventories_controller.rb, app/models/ability.rb, app/models/packages_inventory.rb, app/serializers/api/v1/package_actions_serializer.rb, app/serializers/api/v1/package_serializer.rb, app/serializers/api/v1/stockit_item_serializer.rb, app/serializers/api/v1/version_serializer.rb, config/locales/en.yml, config/locales/zh-tw.yml, config/routes.rb, lib/goodcity/errors.rb, spec/controllers/api/v1/packages_inventories_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3185
FEATURE: On history tab in Item it shows comprehensive history of Actions and version changes applied on Item.
=> GCW-3185- Comprehensive Packages history

db/permissions_roles.yml
As in the description. 
We will take the action of separating stock login and admin app login in a different PR
=> Allowing supervisors to do message actions in stock APP

app/models/concerns/user_search.rb, app/models/user.rb, lib/classes/resync_duplicate_users.rb, lib/tasks/resync_duplicate_users.rb, spec/controllers/api/v1/authentication_controller_spec.rb, spec/lib/classes/resync_duplicate_users_spec.rb, spec/models/user_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3215
Handles the case insensitivity while creating users
User login, User creation
=> Gcw 3215 case insensitive matching

app/controllers/api/v1/requested_packages_controller.rb, app/models/ability.rb, app/serializers/api/v1/requested_package_serializer.rb, config/routes.rb, lib/classes/cart_checkout.rb, spec/controllers/api/v1/requested_packages_controller_spec.rb, spec/serializers/api/v1/requested_package_serializer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3186
FEATURE: Adds quantity changes in requested_packages
=> GCW-3186-Adds quantity changes in requested_packages

spec/controllers/api/v1/gc_organisations_controller_spec.rb, spec/controllers/api/v1/messages_controller_spec.rb, spec/models/orders_package_spec.rb
Fixes few of the random test case failures occurring due to Timezone issues and Messages
=> Fix the random failing of specs in circleci

spec/models/orders_package_spec.rb
=> Fix Timecop usage

app/models/concerns/package_filtering.rb, spec/models/concerns/package_filtering_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3221
search packages by package-type-code
=> GCW-3221 search packages by package-type-code

app/models/concerns/package_filtering.rb, spec/models/concerns/package_filtering_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3221
Search package by package-type-name
=> GCW-3221 search package by package-type-name

app/models/package.rb, config/secrets.yml, features/orders_packages_actions.feature, features/step_definitions/orders_packages_actions_steps.rb, features/support/env.rb, spec/controllers/api/v1/packages_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-2962
Adds validation for uniqueness of inventory number after stockit has been disabled
All Package related operations involving Inventory number
=> GCW-2962 Add Inventory Number validation - Post Stockit

spec/models/concerns/package_filtering_spec.rb
=> Fix Package Filtering Spec

app/controllers/api/v1/packages_controller.rb, app/serializers/api/v1/stockit_item_serializer.rb, spec/controllers/api/v1/packages_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3230
FEATURE: This PR adds subforms versions along with package versions in `versions` endpoint.
=> GCW-3230- Adding versioning on Subforms

app/models/package.rb, app/serializers/api/v1/stockit_item_serializer.rb
This PR fixes
- Changing default value to null during package create.
- add location_id in stockit_item_serializer.
=> FIX => Saleable field bug

lib/classes/package_detail_builder.rb
Fixed rollbar error: https://rollbar.com/crossroads_it/api.goodcity/items/3383/
=> fixed rollbar error at package create/update

app/models/ability.rb, spec/controllers/api/v1/orders_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3217
BUG: Order notes could not be updated in terminal states (e.g. closed)
=> Allow order update in all states

app/models/package.rb
Fix creation of package without inventory number. (creation of item from admin app)
=> fixed creation of package without inventory number

app/models/concerns/push_updates_minimal.rb, app/models/image.rb, app/models/package.rb
https://jira.crossroads.org.hk/browse/GCW-1605
This PR fixes live update issue with images (on adding new images to items, packages, Updating favorite images, Deletion of images)
=> GCW-1605 fixed live-update of images

app/controllers/api/v1/users_controller.rb, app/models/user.rb, app/serializers/api/v1/user_profile_serializer.rb, app/serializers/api/v1/user_serializer.rb, config/initializers/constants.rb, db/migrate/20200817133634_add_language_to_users.rb, db/schema.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/models/user_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3273
preferred_language for user
=> GCW-3273 preferred_language for user

app/models/ability.rb, db/permissions_roles.yml, spec/models/abilities/user_abilities_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3277
allow stock-fulfilment and stoc-administrator roles to read user data
=> GCW-3277 allow stock permissions to read user data

app/models/ability.rb, app/models/concerns/manage_user_roles.rb, app/models/concerns/user_search.rb, app/models/permission.rb, app/models/role.rb, app/models/user.rb, db/migrate/20200814124000_add_expiry_date_to_user_roles.rb, db/schema.rb, features/step_definitions/user_login_steps.rb, features/user_login.feature, spec/factories/user_roles.rb, spec/factories/users.rb, spec/models/user_role_spec.rb, spec/models/user_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3274
expiry-date for user-roles
=> GCW-3274 expiry-date for user-roles

app/models/organisation.rb, spec/controllers/api/v1/gc_organisations_controller_spec.rb, spec/models/organisation_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3284
=> GCW-3284 Add Registration Uniqueness Validation

app/serializers/api/v1/offer_company_serializer.rb, spec/serializers/api/v1/offer_company_serializer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3317
FEATURE: Adds notes in OfferCompany serializers
=> GCW-3179-Added notes in offer company serializer

config/locales/en.yml, config/locales/zh-tw.yml
https://jira.crossroads.org.hk/browse/GCW-3284
=> Adding model error translation

spec/lib/goodcity/tasks/organisation_tasks_spec.rb
=> Fix organisation task spec

config/deploy.rb
=> Fix Capistrano lock version

config/initializers/log_formatting.rb
Fix Sidekiq Logging for Sidekiq version 6.x.x
=> Fix Sidekiq Logging

Gemfile, Gemfile.lock
=> Downgrade sidekiq version

app/services/gogovan.rb, spec/services/gogovan_spec.rb
Fix GoGoVan Issue of Parsing to DateTime
=> Fix GoGoVan Issue of Parsing to DateTime

config/locales/en.yml, config/locales/zh-tw.yml
https://jira.crossroads.org.hk/browse/GCW-3280
BUG: Added missing chinese translation
=> QA-fix-Required translation for add user form added

app/controllers/api/v1/packages_controller.rb, app/models/concerns/operations/designation_operations.rb, app/models/concerns/operations/stock_operations.rb, app/serializers/api/v1/orders_package_serializer.rb, db/migrate/20201006145926_add_shipping_number_to_orders_packages.rb, db/schema.rb, spec/models/concerns/operations/designation_operations_spec.rb, spec/models/concerns/operations/stock_operations_spec.rb, spec/models/orders_package_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3314
shipping_number field for orders_packages
=> GCW-3314 shipping_number field for orders_packages

app/controllers/api/v1/orders_packages_controller.rb, app/models/concerns/orders_package_search.rb, app/models/orders_package.rb, spec/controllers/api/v1/orders_packages_controller_spec.rb, spec/models/orders_package_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3311
- Add query for searching, filtering and sorting orders_packages for given order_id.
=> GCW-3311- sorting & filtering of goods on an order view

app/serializers/api/v1/restriction_serializer.rb, db/restrictions.yml, lib/tasks/create_restrictions.rake, spec/factories/restriction.rb, spec/serializers/api/v1/restriction_serializer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3328
BUG: Serializer error in restriction and added specs for the same
=> GCW-3328-Added Changes for constraints field

app/controllers/api/v1/users_controller.rb, app/models/concerns/fuzzy_search.rb, app/models/concerns/user_search.rb, app/models/organisation.rb, app/models/user.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/models/user_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3287
This PR applies Fuzzy search for users
=> Gcw 3287- Use fuzzy search for Users

app/controllers/api/v1/packages_controller.rb, app/jobs/print_label_job.rb, config/locales/en.yml, config/locales/zh-tw.yml, spec/controllers/api/v1/packages_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3301
This PR accepts `tag` params from app and print label on favourite printer as per tag params.
=> GCW-3301- Selecting default printer while doing `print_label` command

app/models/concerns/operations/order_fulfilment_operations.rb, config/locales/en.yml, config/locales/zh-tw.yml, spec/models/concerns/operations/order_fulfilment_operations_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3313
fixed issue with dispatching quantity more than designated
=> GCW-3313 fixed issue with dispatching quantity more than designated

app/controllers/api/v1/users_controller.rb, app/models/user.rb, app/serializers/api/v1/user_details_serializer.rb, app/serializers/api/v1/user_serializer.rb, spec/controllers/api/v1/users_controller_spec.rb
:ambulance: HotFix For https://jira.crossroads.org.hk/browse/GCW-3376
=> GCW-3376 Fix user charity search hotfix

db/migrate/20201027092800_add_dimension_columns_to_package_types.rb, db/schema.rb, spec/models/package_type_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3297
dimension fields in package-types
=> GCW-3297 dimension fields in package-types

db/permissions_roles.yml
https://jira.crossroads.org.hk/browse/GCW-3378
Update `permission_roles.yml` for reviewer specific permission
=> Update Permission for Review Role

spec/controllers/api/v1/holidays_controller_spec.rb, spec/controllers/api/v1/items_controller_spec.rb, spec/lib/classes/packages_inventories_importer_spec.rb
=> Fix Random failing specs

app/controllers/api/v1/ability.rb, app/controllers/api/v1/offers_controller.rb, app/models/offer.rb, config/routes.rb, spec/controllers/api/v1/offers_controller_spec.rb, spec/models/offer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3285
This PR adds "resume_receiving" action to transition offer from Received to Receiving state.
=> GCW-3285- transition offer from Received to Receiving

app/controllers/api/v1/user_roles_controller.rb, spec/controllers/api/v1/user_roles_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3283
fixed issue with role-update
=> GCW-3283 fixed issue with role-update

config/locales/en.yml, config/locales/zh-tw.yml
BUG: Fix random failing tests of missing order translation
=> Fix random failing tests of missing order translation

app/models/order.rb, spec/models/order_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3306
FEATURE: Orders work regardless of detail_type
=> GCW-3306 Orders work regardless of detail_type

app/models/user.rb, spec/models/user_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3408
Updated user validations
- allow the disabled user to have blank mobile and email
- reset email-verified and mobile-verified fields on the update of mobile and email
=> GCW-3408 Updated user validations

app/controllers/api/v1/packages_controller.rb, app/models/package.rb, spec/controllers/api/v1/packages_controller_spec.rb
FEATURE: QA fixes for total quantity counts in box and pallets
=> GCW-3395-QA fixes for adding total box and pallet contents

app/models/concerns/offer_filtering.rb, app/models/offer.rb, spec/controllers/api/v1/offers_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3399
FEATURE: Admin - New offers list on homepage to show count & alert count
=> GCW-3399 Adding New Offers count in summary response

app/controllers/api/v1/packages_controller.rb, app/models/concerns/package_filtering.rb, spec/models/concerns/package_filtering_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3387
updated package-filtering by package-type-code
=> GCW-3387 updated package-filtering by package-type-code

app/controllers/ability.rb, app/controllers/api/v1/ability.rb, db/permissions_roles.yml, spec/controllers/api/v1/abilities/offer_abilities_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3419
FEATURE: Stock users have permission to view offers fix
=> GCW-3419-Added  permission to search offers for Stock Users

app/services/azure_notifications_service.rb
https://jira.crossroads.org.hk/browse/GCW-3423
fix payload for notifications
=> GCW-3423 fix payload for notifications

app/models/orders_package.rb, app/models/package.rb, spec/models/concerns/operations/order_fulfilment_operations_spec.rb
=> FIX: package_locations were autodeleted when received_quantity = 1

app/controllers/api/v1/ability.rb, app/controllers/api/v1/user_favourite_serializer.rb, app/controllers/api/v1/user_favourites_controller.rb, app/models/concerns/auto_favourite.rb, app/models/package.rb, app/models/package_type.rb, app/models/user_favourite.rb, config/routes.rb, db/migrate/20201126092838_create_user_favourites.rb, db/schema.rb, spec/controllers/api/v1/user_favourites_controller_spec.rb, spec/factories/user_favourites.rb, spec/models/user_favourite_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3416
This PR adds `user_favourites` model to display recently used package_types.
=> GCW-3416- Show recently used `package_type` on `package_type` selection overlay

app/controllers/api/v1/packages_controller.rb, spec/controllers/api/v1/packages_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3426
FEATURE: Remove set of fields from box and pallet
=> GCW-3426 Remove some set of fields from box and pallet

app/models/user_favourite.rb, db/migrate/20201221042717_add_indexes_to_user_favourites.rb, db/schema.rb, spec/models/orders_package_spec.rb, spec/models/user_favourite_spec.rb
=> Correct the indexes on user_favourites table

config/deploy.rb
Add Clear cache in Capistrano deployment
=> Add Clear cache in Capistrano deployment

app/models/package.rb, lib/tasks/packages.rake, spec/models/package_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3441
Set offers-packages for inventorized packages
=> GCW-3441 Set offers-packages for inventorized packages

app/models/concerns/auto_favourite.rb, app/models/user_favourite.rb, spec/models/orders_package_spec.rb, spec/models/user_favourite_spec.rb
1. Use find_or_initialize_by instead of first_or_initialize
2. Fix random specs fails
=> Use find_or_initialize_by instead of first_or_initialize

spec/models/package_set_spec.rb, spec/models/user_spec.rb
=> Fix random failure specs

config/deploy.rb
=> Add capistrano clear rails cache hook

app/controllers/api/v1/users_controller.rb, app/models/concerns/mentionable.rb, config/initializers/constants.rb, spec/controllers/api/v1/users_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3388
=> GCW-3388 Add restrictions for mentioning users

app/controllers/api/v1/offers_controller.rb, spec/controllers/api/v1/offers_controller_spec.rb
=> FIX: Only staff member can include organisations when fetching offers

config/environments/production.rb, config/environments/staging.rb
=> Add env for authentication and starttls vars

app/mailers/application_mailer.rb, app/mailers/goodcity_mailer.rb, app/mailers/goodcity_order_mailer.rb, config/initializers/constants.rb, spec/mailers/goodcity_mailer_spec.rb, spec/mailers/goodcity_order_mailer_spec.rb
Use different from email address for order and general mails
=> Use different from email address for order and general mails

app/views/goodcity_order_mailer/send_appointment_confirmation_email.html.erb, app/views/goodcity_order_mailer/send_order_confirmation_pickup_email.html.erb
=> Add https links

app/views/goodcity_order_mailer/send_order_confirmation_delivery_email.html.erb
Add missing content in mailer view
=> Add missing content in mailer view

app/controllers/api/v1/authentication_controller.rb, spec/controllers/api/v1/authentication_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3491
Adds default language
=> GCW-3491 Set preferred language for current_user

app/controllers/api/v1/stocktakes_controller.rb
Code climate fixes for stocktake_controller
=> Code climate suggestions

app/serializers/api/v2/offer_serializer.rb
Fix codeclimate warnings for offers_serializer
=> Fix codeclimate warnings for offers_serializer

app/controllers/api/v1/offers_controller.rb, app/controllers/api/v2/shareables_controller.rb, app/models/concerns/offer_filtering.rb, app/serializers/api/v2/package_serializer.rb, spec/controllers/api/v1/offers_controller_spec.rb, spec/controllers/api/v2/shareables_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3490
FEATURE: Enhance shared offers
=> GCW 3490 enhance shared offer feature

app/models/user_role.rb
This PR fixes lives_sync issue of user_role on browse app. 
=> FIX=> live sync of  user_role on browse app

app/models/package.rb, lib/classes/valuation_calculation_helper.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/models/concerns/valuation_calculator_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3509
FEATURE: Rounds up the valueHkDollar and default value up to 2 decimal place
=> GCW-3509-Save valueHkDollar value upto 2 deimals

spec/controllers/api/v1/packages_controller_spec.rb
=> Created seperate specs for updation and creation of valueHkDollar

config/deploy.rb
=> Change Capistrano lock version

config/initializers/log_formatting.rb
Update sidekiq logging for Sidekiq v6
=> Update sidekiq logging for v6

lib/classes/manage_location.rb, lib/tasks/locations.rake, spec/lib/classes/manage_location_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3443
rake task to clear and merge locations
=> GCW-3443 rake task to clear and merge locations

app/models/item.rb, app/models/offer.rb, app/serializers/api/v1/offer_serializer.rb, spec/models/item_spec.rb, spec/models/offer_spec.rb, spec/serializers/api/v1/offer_serializer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3568
Fixed issue with having private messages in donor app
=> GCW-3568 fixed donor messages response

app/controllers/api/v2/authentication_controller.rb, app/models/role.rb, app/models/user.rb, config/routes.rb, spec/controllers/api/v2/authentication_controller_spec.rb
`/api/v2/auth/goodchat`
This endpoint will be called by the goodchat service in order to allow staff members to join
=> ADD: goodchat authentication endpoint

app/models/order.rb, config/locales/en.yml, config/locales/zh-tw.yml, spec/controllers/api/v1/requested_packages_controller_spec.rb, spec/models/order_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3533
This PR adds validation for online orders to have orders_package before submitting. Also, fixed test cases as per changes.
=> GC-3533-Validation should be added to ensure packages are present before creating online orders

app/controllers/api/v1/ability.rb, spec/controllers/api/v1/abilities/message_abilities_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3201
FEATURE: Adding message centre for browse app
=> GCW 3201 Browse messaging center

app/models/user.rb, app/services/slack_pin_service.rb, app/services/twilio_service.rb, spec/models/user_spec.rb
- Fix SMS being sent to wrong mobile number
=> GCW-3537 Fix SMS being sent to wrong mobile number

app/models/user.rb, spec/models/user_spec.rb
https://jira.crossroads.org.hk/browse/GCW-1474
Set proper preferred language while new user signup
=> GCW-1474 Set Preferred language while new user signup

app/models/concerns/cacheable_json.rb
https://jira.crossroads.org.hk/browse/GCW-3598
=> GCW-3598 fixed cache key

.gitignore, db/migrate/20210407050441_add_additional_country_fields.rb, db/schema.rb, lib/classes/stockit_data_importer.rb, lib/tasks/stockit_data_import.rake
https://jira.crossroads.org.hk/browse/GCW-3046
This ticket covers a variety of StockIt data mapping tasks that were left unfinished
After the deployment
- Run `rails goodcity:data:stockit_data_import RAILS_ENV=<env>`
=> GCW-3406 Stockit Migration (RECREATED)

.gitignore, db/migrate/20210407050441_add_additional_country_fields.rb, db/schema.rb, lib/classes/stockit_data_importer.rb, lib/tasks/stockit_data_import.rake
https://jira.crossroads.org.hk/browse/GCW-3046
FEATURE: applies some data fixes left over from stockit days
=> Gcw 3046 stockit migration redo

lib/classes/stockit_data_importer.rb
https://jira.crossroads.org.hk/browse/GCW-3046
BUG: Now handles cases where more than one Stockit organisation had the same name.
=> Org mapping now understands stockit orgs with the same name

lib/classes/stockit_data_importer.rb
https://jira.crossroads.org.hk/browse/GCW-3046
=> Prepared code to run resiliently

lib/goodcity/user_utils.rb, spec/lib/goodcity/user_utils_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3629
Fixed merging of user details and precedence of values
=> GCW-3629 fixed user-details merge

app/controllers/api/v1/package_types_controller.rb, app/models/package_type.rb, app/serializers/api/v1/package_type_serializer.rb, config/routes.rb, db/migrate/20210602085849_update_package_types.rb, db/schema.rb, db/seeds.rb, spec/controllers/api/v1/package_types_controller_spec.rb, spec/factories/package_types.rb, spec/models/package_type_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3642
Update package-types, rename allow_stock to allow_packages
=> GCW-3642 Update package-types, rename allow_stock to allow_packages

app/controllers/api/v1/offers_controller.rb, spec/controllers/api/v1/offers_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-2705
avoid loading draft offers for staff-user
=> GCW-2705 avoid loading draft offers for staff-user

app/models/delivery.rb, app/models/item.rb, app/serializers/application_serializer.rb, app/services/labels/base_label.rb, app/services/print_label.rb, app/services/push_service.rb, app/services/slack_pin_service.rb, app/services/twilio_service.rb
=> Code climate fixes

app/models/concerns/stocktake_processor.rb, app/models/stocktake.rb, spec/models/concerns/stocktake_processor_spec.rb, spec/models/stocktake_spec.rb
- Improve performance of `Stocktake::process_stocktake`
=> [0.22.1] Release stocktake performance fix

app/models/concerns/stocktake_processor.rb, app/services/push_service.rb, spec/services/push_service_spec.rb
=> FIX: disable push updates during stocktake processing

app/controllers/api/v1/offers_controller.rb, app/models/concerns/share_support.rb, app/models/offer.rb, app/models/shareable.rb, spec/controllers/api/v1/offers_controller_spec.rb, spec/models/offer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3665
Set offer shareable expires_at on offer close
=> GCW-3665 Set offer shareable expires_at on offer close

app/controllers/ability.rb, app/controllers/api/v1/ability.rb, app/controllers/api/v1/messages_controller.rb, app/controllers/api/v1/offer_responses_controller.rb, app/models/concerns/message_subscriptions.rb, app/models/concerns/push_updates_for_message.rb, app/models/concerns/push_updates_for_subscription.rb, app/models/message.rb, app/models/offer.rb, app/models/offer_response.rb, app/models/user.rb, app/serializers/api/v1/notification_serializer.rb, app/serializers/api/v1/offer_response_serializer.rb, config/routes.rb, db/migrate/20210620222418_create_offer_responses.rb, db/permissions_roles.yml, db/schema.rb, spec/controllers/api/v1/abilities/message_abilities_spec.rb, spec/controllers/api/v1/messages_controller_spec.rb, spec/controllers/api/v1/offer_responses_controller.rb, spec/factories/offer_responses.rb, spec/models/concerns/push_updates_for_message_spec.rb, spec/models/offer_response_spec.rb, spec/serializers/api/v1/notification_serializer_spec.rb, spec/serializers/api/v1/offer_response_serializer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3663
FEATURE: Adds offer response table
=> GCW-3663-Add offer response table

lib/classes/package_detail_builder.rb, spec/lib/classes/package_detail_builder_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3674
FEATURE: Fix data loss issue in subforms
=> GCW-3674-Fix breaking of subform dropdwns

app/views/goodcity_order_mailer/send_order_confirmation_pickup_email.en.html.erb, app/views/goodcity_order_mailer/send_order_confirmation_pickup_email.zh-tw.html.erb, spec/mailers/goodcity_order_mailer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3640
FEATURE: Item requested in order is not present order confirmation delivery email fix
=> GCW-3640-Item requested not present issue in order confirmation delivery email fix

app/controllers/api/v2/shareables_controller.rb, app/serializers/api/v2/offer_serializer.rb, spec/controllers/api/v2/shareables_controller_spec.rb, spec/serializers/api/v2/offer_serializer_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3664
FEATURE: Adding expires_at to shareable serializers
=> GCW-3664-Adding expires_at to shareable serializers

app/models/order.rb, app/views/goodcity_order_mailer/send_appointment_confirmation_email.zh-tw.html.erb, app/views/goodcity_order_mailer/send_order_confirmation_delivery_email.zh-tw.html.erb, app/views/goodcity_order_mailer/send_order_confirmation_pickup_email.zh-tw.html.erb
https://jira.crossroads.org.hk/browse/GCW-3640
BUG: Fix Chinese package type issue
=> Add chinese translation for package type

app/controllers/api/v1/offers_controller.rb, app/models/concerns/offer_filtering.rb, spec/controllers/api/v1/offers_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3709
FEATURE: Add filter for including and excluding expiry offer shareable
=> GCW-3709-Add filter for including and excluding expiry offer shareables

app/models/offer.rb, spec/controllers/api/v1/offers_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3711
FEATURE: Admin - Provides a link to active shares from the home screen
=> GCW-3711 Add link to active shares from home page

app/controllers/api/v1/messages_controller.rb, spec/controllers/api/v1/messages_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3715
fixed messages index, removed unscoped
=> GCW-3715 fixed messages index, removed unscoped

app/controllers/api/v1/ability.rb, spec/controllers/api/v1/messages_controller_spec.rb
https://jira.crossroads.org.hk/browse/GCW-3726
FEATURE: Allow chat on shareable offers for users who have previously responded
=> GCW-3726-Allow chat on expired offers

app/controllers/api/v1/access_passes_controller.rb, app/models/concerns/offer_filtering.rb
https://jira.crossroads.org.hk/browse/GCW-3734
=> Hotfix for order email bug

app/controllers/api/v1/packages_controller.rb, app/models/package.rb, db/migrate/20220130120417_add_max_order_quantity_to_packages.rb, db/schema.rb, spec/controllers/api/v1/packages_controller_spec.rb, spec/factories/packages.rb, spec/models/package_spec.rb
Adds a field to package to limit the max quantity ordered.
=> :sparkles: ADD: package max order quantity

app/controllers/ability.rb, app/controllers/api/v1/ability.rb, app/controllers/api/v1/users_controller.rb, app/jobs/user_safe_delete_job.rb, config/initializers/lib_goodcity.rb, config/routes.rb, db/permissions_roles.yml, lib/goodcity/user_safe_delete.rb, spec/controllers/api/v1/abilities/user_abilities_spec.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/jobs/user_safe_delete_job_spec.rb, spec/lib/goodcity/user_safe_delete_spec.rb
New feature enables a user to delete their personal information.
=> User safe delete code

app/controllers/api/v1/users_controller.rb, app/controllers/api/v2/users_controller.rb, app/models/user.rb
Resolved minor rubocop warning for resource `User`. [Hacktoberfest PR ]
cc @steveyken
=> Fix minor rubocop warnings for user resource

Gemfile.lock
FEATURE: Nokogiri required a security update
=> Update nokogiri for secuty vuln
